### ISSUE TITLE
HTML Editor Plugins

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#100]
There are 4 HTML Editor plugins in the Equella source code repo:
- [after the deadline](https://github.com/equella/Equella/tree/master/Source/Integration/HTMLEditorPlugins/sourceFiles/after_the_deadline)
- [ice](https://github.com/equella/Equella/tree/master/Source/Integration/HTMLEditorPlugins/sourceFiles/ice)
- [wiris](https://github.com/equella/Equella/tree/master/Source/Integration/HTMLEditorPlugins/sourceFiles/wiris)
- [example plugin](https://github.com/equella/Equella/tree/master/Source/Integration/IntegrationPack/sourceFiles/htmleditor/samples/bacon_example)

'after the deadline', and 'ice' are GPL v2, and wiris is a placeholder for the plugin http://www.wiris.com/en/solutions/tinymce

Need to decide how to handle the GPL licenses, along with wiris, and possibly move these 4 plugins into their own repo.

Once the appropriate repo is determined, please update the docs [here](https://github.com/equella/equella.github.io/blob/master/guides/HTMLEditorPluginGuide.md).

**Comment by cbeach47** [comment]
Also, for WIRIS, they mention Equella Pearson on their [solutions](http://www.wiris.com/en/solutions) site.  Might be good to reach out and change that over to Apereo.  

The [equella solutions](http://www.wiris.com/en/solutions/equella) site also has a broken link for 'Installation Instructions'.

**Comment by cbeach47** [comment]
Moved them into the docs repo [here](https://github.com/equella/equella.github.io/tree/master/example-scripts), along with the 'bacon example' HTML Editor plugin

**Comment by cbeach47** [comment]
Waiting on the naming decision, then we can reach out to WIRIS to get the doco link changed.

**Comment by emcgarrahan** [comment]
Diego to reach out to WIRIS to inform them of appropriate updates.

**Comment by ddelblanco** [comment]
I reached to them. They are testing the integration with the new version and they needed (10/18/2017) some help so they are going to reach Chris.
