### ISSUE TITLE
Autotest failures in new UI

### ISSUE THREAD

**Issue by doolse** [openequella/openEQUELLA#1008]
**Describe the bug**
While getting the tests to run with the new UI switched on I have found some legitimate failures to due bugs (e.g. not problems with the test itself):

- com.tle.webtests.test.searching.manage.ManageResourcesSearchTest - Add criteria button does nothing on first try
- com.tle.webtests.test.searching.manage.BulkScriptExecutionTest - partial form update is broken
- com.tle.webtests.test.users.TokenLoginTest - token errors don't show
- com.tle.webtests.test.admin.ServerMessageTest - just doesn't show at all
- com.tle.webtests.test.drm.DRMPrivilegeTest
- com.tle.webtests.test.contribute.DiscoverabilityTest - meta tags don't appear, broken markup breaks links
- com.tle.webtests.test.contribute.controls.RepeaterTest - runwizard link tries to run more than once
- com.tle.webtests.test.admin.ServerMessageTest - Server message doesn't show at all on new UI
- com.tle.webtests.test.cal.CALViolationTest - Error shows in an unfriendly way
- com.tle.webtests.test.usersscripts.UserScriptTest - Creating a new script keeps previous title
- com.tle.webtests.test.cal.CALAgreementTest - "Accept" on agreement doesn't work

**Platform:**

- OpenEquella Version: 2019.1

**Comment by cathfitz** [comment]
Separate issue created for Server Message https://github.com/apereo/openEQUELLA/issues/1086

**Comment by mrblippy** [comment]
New issue for Manage Resources add criterion button #1088

**Comment by mrblippy** [comment]
New issue created for DiscoverabilityTest #1089
