### ISSUE TITLE
Implement the ability for the filestore to reside on the host

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1044]
Could be part of a larger discussion with docker-compose and how to architect docker with openEQUELLA for production use.  

Specifically for this ticket, it'd be useful to have a flag for the Dockerfile to use a filestore on a host directory.

**Comment by edalex-ian** [comment]
Heya @cbeach47 

This is already supported. You simple map a docker volume to the same path as you configure to be used as the filestore. We use this in our clusters and provide a volume which is in turn is a NFS mount on the hosts.

Is that the kind of thing you're after?
