### ISSUE TITLE
Setup process for pre-installed oEQ images in docker hub

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1045]
Especially to help aid new adopters, it'd be useful to have a pre-installed openEQUELLA image of each major version get pushed to DockerHub under Apereo.  The image would have to be consistent with Apache v2 licensing.

**Comment by edalex-ian** [comment]
This would be good indeed. Two things jump to mind though:

1. Does Apereo already have a docker hub setup (or other docker registry); and
2. Before we do this, I'd like some effort spent on optimising the `Dockerfile` to produce a much smaller image - it's currently ~1.5GiB. (Maybe that should be another ticket.)
