### ISSUE TITLE
New ui: Errors in logs when performing actions after session has expired

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1071]
**Describe the bug**
Errors are getting logged in the resource-centre logs whenever a user tries to use legacy content in the new ui (like trying to perform a search). It's likely to confuse astute openequella administrators that like to go through their logs looking for issues.

An example of one of the errors:
![Capture](https://user-images.githubusercontent.com/4625498/60310391-0a644b80-9996-11e9-8a08-13f571fe8e61.PNG)

**To Reproduce**

1. Enable the new ui
2. Perform a search
3. Open up another tab pointing to the same institution
4. Logout of equella
5. Go back to the first tab, and do another search (it should fail because that user is logged out)
6. You should see a corresponding error in the logs

**Platform:**

- OpenEquella Version: 2019.1

**Comment by nelson-edalex** [comment]
1. Login
2. Do a search
3. Open tab 2
4. Logout in tab 2
5. Go back to tab 1 and enter keyword (or add a criteria in facade)
Here, tab 1 did NOT redirect to logon.do but showing 0 result found.
