### ISSUE TITLE
Broken language string in admin console when exporting wizard control

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1083]
**Describe the bug**
Occurs when you right click a wizard control and choose Export
![Capture](https://user-images.githubusercontent.com/4625498/60484367-b4b4d980-9cdc-11e9-9623-91ebd0121d79.PNG)

**To Reproduce**

1. Open up a collection definition Editor
2. Right click a wizard control and click the Export option
3. The file browser will display multiple broken language strings

- OpenEquella Version: 2018.2, 2019.1

**Comment by abidingotter** [comment]
Re-opening.  Should be a trivial fix.

**Comment by cathfitz** [comment]
@abidingotter Tested in unstable and still broken
