### ISSUE TITLE
Facet searching: facets arent returned when search query is only found in attachment content

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1096]
**Describe the bug**
The code that the facet searching uses is setup to not search inside attachments
https://github.com/apereo/openEQUELLA/blob/e5ee7d72a2c42165a65eabc9fcc30cb1b61818ea/Source/Plugins/Core/com.equella.core/src/com/tle/core/freetext/index/ItemIndex.java#L704

Once that third variable is changed to true the facet search endpoint returns the correct data. But i'm not sure why it was configured to not search through attachments (maybe it's just a performance thing?)

An Edalex client found this while they were using the search facets on the new search page in 6.6, but this could affect anyone using the search/facet rest endpoint

**To Reproduce**

Steps to reproduce the `behaviour:`

1. Import the attached schema and collection 
[Collection Definition - TEST of wizard.zip](https://github.com/apereo/openEQUELLA/files/3375770/Collection.Definition.-.TEST.of.wizard.zip)
[Charlie schema.zip](https://github.com/apereo/openEQUELLA/files/3375771/Charlie.schema.zip)
2. Contribute an item in the collection (with the name of 'animal'), and add [animal talk.txt](https://github.com/apereo/openEQUELLA/files/3375750/animal.talk.txt) as an attachment
3. Publish the item
4. got to http://yourequella/yourinstitution/api/search/facet?nodes=%2Fitem%2Flom%2Fgeneral%2Ftitle&q=lamb&breadth=10&showall=false in your browser
(eg. https://rc.dev.edalex.com/charlie/api/search/facet?nodes=%2Fitem%2Flom%2Fgeneral%2Ftitle&q=lamb&breadth=10&showall=false )
5. No data will be returned

**Expected behavior**

The following JSON should have been returned

```
{
  "results": [
    {
      "term": "animal",
      "count": 1
    }
  ]
}
```

**Platform:**

- OpenEquella Version: 6.6, 2018.2, 2019.1
- OS: windows 10
- Browser chrome

**Comment by mrblippy** [comment]
Since this fix touched code used by hierarchies we also need to do a quick sanity test of the hierarchy feature. Just make sure the counts for a hierarchy topic make sense

**Comment by edalex-ian** [comment]
So I believe this has all been done and tested. As a result, maybe it's ready to close @mrblippy or @cathfitz ?
