### ISSUE TITLE
Look into change to GitHub releases page and the work involved with migrating away from version server.

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#1108]

**Comment by edalex-ian** [comment]
Initial review of this done and feature outlined in #1269. With the release of 2019.1.1 hopefully we can get this done for 2019.2.

**Comment by cbeach47** [comment]
Code build is still in progress.

**Comment by edalex-ian** [comment]
Closing, as released in 2019.1.2.
