### ISSUE TITLE
CAS filter not being trigged in new UI properly

### ISSUE THREAD

**Issue by doolse** [openequella/openEQUELLA#1116]
**Describe the bug**
With the new UI turned on and have CAS SSO setup, you will bypass the CAS filter on the logon page if the new UI does client side redirects.

**To Reproduce**

1. Configure a CAS server or use demo one - https://casserver.herokuapp.com/cas/ casuser/Mellon - ensure you have a local user "casuser"
2. Ensure the new UI is turned on
3. Go to http://inst/home.do
4. You should be redirected to the CAS logon page but instead see the internal logon page

- OpenEquella Version: [2019.1]

**Comment by edalex-ian** [comment]
Added 'Tech debt' to override 'stale' as we have PR #1144 in play. Just waiting for @doolse or @PenghaiZhang to resolve conflicts so that we can merge.
