### ISSUE TITLE
New UI: <XML> and ~ view showing 404 for items with DRM

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1125]
**Describe the bug**
Only happens in 2018.2
Seems to be an issue with the LegacyContent api

**To Reproduce**

1. Ensure the new ui is enabled
2. Contribute/publish an item that contains an attachment with drm
3. On the item summary page append <XML> or ~ to the end of the url
3. You will see a 404 error

**Expected behavior**
XML for the item should displayed when <XML> is appended to an item url

**Platform:**

- OpenEquella Version: 2018.2
- OS: windows 10
- Browser [e.g. Chrome, Firefox]

**Comment by SammyIsConfused** [comment]
Reopening, as this came up in support (discovered and reported by Carl, not by a client.)

**Comment by edalex-ian** [comment]
@PenghaiZhang or @snehanaik22 , in your recent DRM work have you come across this issue? Is it still an issue?

Do we need @cathfitz to schedule it in?

**Comment by edalex-ian** [comment]
Seems everyone (@PenghaiZhang , @snehanaik22 and @cathfitz ) missed my last comment on this one. I will follow up more directly.

**Comment by PenghaiZhang** [comment]
Tested on `2022.1` and `<XML>` and `~` view work fine.
