### ISSUE TITLE
<meta> tags are missing in new UI

### ISSUE THREAD

**Issue by PenghaiZhang** [openequella/openEQUELLA#1148]
In the new UI, if a collection enables discoverability,  two head <meta> tags will be missing after doing actions such as publishing items.
Also, opening "harvest.do" from new UI will result in the Robots meta tag missing.

**To Reproduce**

1. Contribute an item from a collection which enables discoverability.
2. In the Resource summary page, open the develop tool, inspect HTML elements and go to head section.

**Expected behavior**
Two meta tags should be added into head
In old UI, you can see these two tags.
![image](https://user-images.githubusercontent.com/47203811/62433606-734e9880-b778-11e9-9287-9c11ec7b3784.png)

**Screenshots**
In new UI, you can't see these two tags.
![image](https://user-images.githubusercontent.com/47203811/62433685-c6285000-b778-11e9-8870-8894a89578a5.png)

**Stacktrace**
None

**Platform:**

- OpenEquella Version: 2019.1 / 2019.2
- OS: Ubuntu 18.04
- Browser Chrome

**Additional context**
None

**Comment by edalex-ian** [comment]
@SammyIsConfused tested this yesterday, closing.
