### ISSUE TITLE
Selection session: extra css files being loaded in Skinny selection sessions

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1159]
**Describe the bug**
In 6.6 there is a minified bootstrap (com.equella.core/bootstrap/css/bootstrap.min.css) that is getting loaded on the search page, that screws up the styling of various elements. Seems to be triggered by first ajax event that happens on the page.

When selection session first loads:
![before](https://user-images.githubusercontent.com/4625498/62668340-dd607b00-b9ce-11e9-89e1-3c5eb655e522.PNG)

After an ajax event happens (like performing a search:
![after](https://user-images.githubusercontent.com/4625498/62668385-04b74800-b9cf-11e9-8d4e-5e1225cd60bd.PNG)

This seems to be specific to 6.6 using selection sessions. The symptoms seems similar to the ie issues we found a while ago. But the root cause looks to be different. This happens in all browsers.
 

**To Reproduce**

1. Go to a moodle that has the openEQUELLA moodle module installed
2. On the openEQUELLA Resource page sill out the relevant fields. Make sure you enter searchThin into the openEQUELLA URL field.
![moodle](https://user-images.githubusercontent.com/4625498/62668796-8f4c7700-b9d0-11e9-97ac-b95b05468705.PNG)
3. Start a selection session
4. Perform a search
5. See some dodgy styling

**Platform:**

- OpenEquella Version: 6.6
- OS: windows 10
- Browser all browsers

**Comment by timrattle** [comment]
This is still an issue.
