### ISSUE TITLE
"Item not found" when clicking fullscreen on DRM-enabled attachment in new UI

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#1160]
**Describe the bug**
In 2019.1, when using the new UI, an incorrect "Item not found" error displays when clicking "Fullscreen" on a DRM-protected attachment.
`DRMTest` highlighted this issue. 

**To Reproduce**
1. Run `DRMTest` in the new UI.

OR

1. Go to the Resource Summary page of an item with DRM on the attachments, using an account that requires agreement of this DRM before viewing.
2. Click "Fullscreen".
3. See error.

**Expected behavior**
The DRM accept/reject dialog should pop up, and on accept it should show the attachment fullscreen.

**Screenshots**
![image](https://user-images.githubusercontent.com/24543345/62670291-12240080-b9d6-11e9-8fb5-43490398352b.png)

**Platform:**

- OpenEquella Version: 2019.1
- OS: Ubuntu 19.04
- Browser: Chrome, Firefox

**Comment by SammyIsConfused** [comment]
Reopening, as this came up in support (discovered and reported by Carl, not by a client.)

**Comment by snehanaik22** [comment]
Tested.
