### ISSUE TITLE
imscc file shows 404 error

### ISSUE THREAD

**Issue by scorpsteals** [openequella/openEQUELLA#1169]
**Describe the bug**
When viewing an IMS package in equella the launch page with the url ending with viewims.jsp shows a 404 error page and the Contents index shows Unnamed. All other navigation links work fine.

**To Reproduce**
Submit an item by uploading an ims package as a content package and select default viewer. View the item via the ims viewer. 

**Expected behavior**
The 404 should not show up instead should show the introduction page. There shouldn't be any unnamed tags on the index.

**Screenshots**
![image](https://user-images.githubusercontent.com/2992160/62872736-1872ef00-bcec-11e9-9780-9ac868c980a0.png)

**Platform:**

OpenEquella Version: [2019.1-Stable.r2.OSE]
OS: [Windows 10]
Browser [Chrome,firefox]

**Comment by cathfitz** [comment]
@scorpsteals Unable to reproduce this problem in openEQUELLA. Seems the problem may be with the specific package.
