### ISSUE TITLE
Improve REST API object creation requests

### ISSUE THREAD

**Issue by abidingotter** [openequella/openEQUELLA#1179]
**Is your feature request related to a problem? Please describe.**
The POST methods (ie usually creation methods) in our REST API will usually return a Location header where you can request the newly created object.  Often times you will simply just want to extract the UUID (or other defaulted values) of the created object, which leaves you with two options:
1. Execute a GET on the Location URL -> Wasted time and bandwidth
2. Parse the Location URL for the UUID -> Error prone & not a guaranteed URL format
  
**Describe the solution you'd like**
Either:
1. The generated ID of any created object could be returned in an additional header
2. A JSON response body is returned for all creation requests
My preference would be option 2, as it would also fill in other defaulted values on the object.

**Comment by cbeach47** [comment]
I like option #2 .  You might consider a parameter in the POST request specifying how much detail you want returned in the JSON.

**Comment by doolse** [comment]
I think option 1 is best because:
1. It's easier to implement. 
2. The very common case is that the data you created is what you sent and you only care about the id.

I think if the most common case for your creation API is that you need some data form the server, then you use both 1 and 2.
