### ISSUE TITLE
Proposal: let's overhaul the url checking feature in oEQ

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1182]
**Is your feature request related to a problem? Please describe.**

The url checking feature in oEQ periodically checks both item XML for URLs, and URL attachments. The way oEQ determines a url to be bad is to make a HTTP request to each url. If the response code  is found in a list that's stored in the code then it marks the url as 'bad'. Once a url has been found to  be 'baad' 5 times the original contributior of the item gets a warning notification and email spam from the oEQ server. 
Once a url has been found to be 'baad' 10 times the user gets more email spam, as well as the url attachment hyperlink getting disabled.

The feature can be disabled via a .properties file. But that property also causes some LMS integration configuration functionality in oEQ to not work. Also, it requires a full oEQ restart to take effect.

Its a good feature in theory, but the amount of support tickets I have seen related to it over the years outweighs any other oEQ feature. The current implementation annoys both users, developers, consultants and support. So many false positives (usually caused by local institution infrastructure) are very hard to debug.

Scenario time:
User gets confused, the url of an attachment they have added has been marked as 'baaad'. But they check it in their browser and it works fine. 

Any bad url support issues cause mental anguish on all fronts. It takes remote client access that we usually can't get. Uni infrastructures are usually locked down (with good reason).

At some point we must ask ourselves if this feature is worth the effort, considering the amount of people it has caused to have a bad time with oEQ 

**Describe the solution you'd like**

Get rid of the url checker entirely

**Describe alternatives you've considered**

Make a web UI config that allows for oEQ admins to specify bad HTTP response codes that the url checker uses. Is it worth the effort to do this though?

OR

Enable oEQ admins to disable the url checker, without affecting any other oEQ functionality

**Additional context**

The majority of the hair I have lost has been due to the url checker. And that's a fact

If you got this far, thank you for reading my long winded rant.

**Comment by mrblippy** [comment]
Here is an example of some outstanding url checker related issues that exist in all oEQ versions after 6.1 (i think that was when the feature got completely rewritten to allow for concurrent checking to take place)

https://github.com/openequella/openEQUELLA/issues/1187
https://github.com/openequella/openEQUELLA/issues/1025
https://github.com/openequella/openEQUELLA/issues/180
https://github.com/openequella/openEQUELLA/issues/213

**Comment by edalex-ian** [comment]
We should discuss this proposal me thinks. Maybe at the CDM.... :thinking:

**Comment by abidingotter** [comment]
Clients would still want this.  If anything was to change, maybe it could be turned off by default, or made to work *only* on link attachments rather than links embedded in HTML etc. (again, another config option)
