### ISSUE TITLE
Open EQUELLA Documentation isn´t available

### ISSUE THREAD

**Issue by mjsantamaria** [openequella/openEQUELLA#1183]
Open EQUELLA Documentation isn´t available in https://www.apereo.org/projects/open-equella

1. Go to 'Open EQUELLA Documentation'
2. Click on 'Documentation for Getting Started', for example
3. See error '404: Sorry, we can’t seem to find this page’s pixylls.'

**Comment by cathfitz** [comment]
Documentation links have been updated
