### ISSUE TITLE
Taxonomy PUT requests for data is broken

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1192]
**Describe the bug**
For the PUT request `/{uuid}/term/{termUuid}/data/{datakey}/{datavalue}` in `TaxonomyResource`, the `datakey` parameter is listed twice instead of once and then the `datavalue`parameter.

This messes up the Swagger UI apidocs.do page as well.

**Platform:**

- OpenEquella Version: 2019.1

**Comment by edalex-ian** [comment]
As part of #1225 the taxonomy REST API implementation has been significantly reworked to match some of the other oEQ REST APIs. This has been merged into `develop` so it could be interesting to see if this has improved things for you.

**Comment by SammyIsConfused** [comment]
Verified and tested in current develop, this now works. Closing.
