### ISSUE TITLE
Adding a new datum to a taxonomy term fails

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1194]
**Describe the bug**
Unable to PUT to `/api/taxonomy/{tax-uuid}/term/{term-uuild}/data/{key-1}/{value-1}`.  oEQ 2019.1 yields the error:
```
{
  "code": 500,
  "error": "Internal Server Error",
  "error_description": "No existing transaction found for transaction marked with propagation 'mandatory'"
}
```

**Platform:**
- OpenEquella Version: 2019.1

**Comment by phette23** [comment]
I think this is a dupe of #1192 but we _really_ need this feature fixed, it basically invalidated an entire week of work I did trying to convert one of our processes from SOAP to the REST API.

**Comment by edalex-ian** [comment]
As part of #1225 the taxonomy REST API implementation has been significantly reworked to match some of the other oEQ REST APIs. This has been merged into `develop` so it could be interesting to see if this has improved things for you.

**Comment by abidingotter** [comment]
This is a separate issue to #1192 , but I have fixed both in one pull request: https://github.com/openequella/openEQUELLA/pull/1333

**Comment by SammyIsConfused** [comment]
Tested and verified in develop. This is now fixed. Closing.
