### ISSUE TITLE
Detail needed permissions for fixed Bb user in LTI/REST scenario

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1197]
Currently it's noted in the 2019.1 features guide: 
> Configure the REST Application in Blackboard > Select a 'Learn User' that has sufficient permissions.

Documentation is need to list the needed permissions instead of just using a 'system admin' user.

**Comment by edalex-ian** [comment]
Heya @cbeach47 

I wonder if we should put doco tickets over in the doco repo?

**Comment by cbeach47** [comment]
opened until the doco issue is created

**Comment by cbeach47** [comment]
Closing in favor of https://github.com/openequella/openequella.github.io/issues/55
