### ISSUE TITLE
Contribution wizard: List box width not correct when dynamically loaded 

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1200]
**Describe the bug**

The width of List Box controls aren't getting set right when dynamically loaded (in a visibility script) during a contribution wizard. Instead of being the full width of the page it's only the width of whatever the placeholder text is.

![wrong](https://user-images.githubusercontent.com/4625498/63902090-fba81c80-ca4a-11e9-9673-ac12230b8c57.PNG)

Specific to stylish select (jquery.stylish-select.js) List Boxes. When you enable accessibility mode (user profile settings) the issue doesn't happen.

Present in both 2018.2 and 2019.1 in old and new ui.

Stylish select was removed and put back into oEQ here https://github.com/openequella/openEQUELLA/commit/df9f40711474ace48d671b8da47eee5dc6411a2a So maybe that has something to do with it?

**To Reproduce**

1. Import this collection 
[Collection Charlie.zip](https://github.com/openequella/openEQUELLA/files/3553400/Collection.Charlie.zip)
2. Open a contribution wizard, and click the checkbox to display the Listbox control
3. Notice the width of the listbox isn't right

**Expected behavior**
![expected](https://user-images.githubusercontent.com/4625498/63902043-b388fa00-ca4a-11e9-99a0-7cfeb75b58d5.PNG)

**Platform:**

- OpenEquella Version: 2018.2, 2019.1

**Comment by abidingotter** [comment]
The problem is that the select is invisible to start with, and so no CSS is applying to it.  Stylish Select then detects the width as whatever the browser says the default width is.
The fix forces 100% width on the dropdown (have to use the !important modifier to override style attribute on the element)
