### ISSUE TITLE
Background job status for long running REST actions

### ISSUE THREAD

**Issue by abidingotter** [openequella/openEQUELLA#1203]
**Is your feature request related to a problem? Please describe.**
I have implemented a "sort whole taxonomy" REST endpoint as part of the new taxonomy sorting feature, however a taxonomy of a modest size (ie. 1000+ terms) will take too long to execute for the whole HTTP request to be held up.  
The GroupActionResource for re-assigning an ID to a user fires off a background event, however there is no way to tell when it's finished.  

**Describe the solution you'd like**
Any long running REST actions should return some sort of job token, which you can use to poll the status of your job.  Status would be limited to either running or finished, unless the job in question could easily report a percent complete status. The status could possibly be polled via a unified Job endpoint, or another endpoint specific to the action taken.
e.g.
``` 
POST taxonomy/[uuid]/sort -> token
GET taxonomy/[uuid]/sort/[token]
```
OR
```
POST taxonomy/[uuid]/sort -> token
GET job/[token]
```

**Describe alternatives you've considered**
There are no alternatives I can think of

**Comment by edalex-ian** [comment]
This is an interesting one, as I've heard from consultants they're finding REST Taxonomy calls are _significantly_ slower than SOAP equivalents. They originally had a script they wrote with REST which took 4 odd hours to run, so they moved it to SOAP and then it took less than an hour. (This was a script run daily for a client with a large taxonomy to re-sort it manually.)

So while yes it could be interesting to undertake then, it's sounding like at least for taxonomies there's an underlying issue with REST usage.

**Comment by abidingotter** [comment]
The REST service doesn't look like it has a lot of overhead over the SOAP one.  We could look into that.  Would be interesting to see both of their scripts.

Even so, my new sorting endpoint does it all in one call (as opposed to thousands of calls they would currently be making), so REST vs SOAP is largely irrelevant with that one.  It would always take longer than the HTTP timeout whether it was REST or SOAP.
