### ISSUE TITLE
Error occurs when trying to save item as draft if Save and Continue is used

### ISSUE THREAD

**Issue by PenghaiZhang** [openequella/openEQUELLA#1204]
**Describe the bug**
When saving an item as a draft, an error occurs.

**To Reproduce**
1. Begin contributing an item
2. Fill some fields and click 'save and continue'
3. Click 'Save' and then click 'Save draft'

**Expected behavior**
The page should display properly

**Screenshots**
![Screenshot from 2019-08-30 16-59-44](https://user-images.githubusercontent.com/47203811/63999942-03012000-cb48-11e9-91d7-96480f51f588.png)
![Screenshot from 2019-08-30 16-59-56](https://user-images.githubusercontent.com/47203811/63999953-072d3d80-cb48-11e9-8437-10631a6e9012.png)

**Stacktrace**
None.

**Platform:**

- OpenEquella Version: 2019.1 / 2019.2 / maybe 2018.2
- OS: Ubuntu
- Browser Chrome

**Additional context**
None

**Comment by cathfitz** [comment]
@PenghaiZhang interestingly, it still saves the draft items
