### ISSUE TITLE
Support preventing "dangerous" scripts from being run

### ISSUE THREAD

**Issue by doolse** [openequella/openEQUELLA#1210]
**Is your feature request related to a problem? Please describe.**

While being extremely powerful, openEQUELLA's scripts are unsuitable to be used in a shared hosting environment because you must trust that a script won't use too many resources as you have a turing complete language at your disposal. It would be nice is we could support a safe subset that is suitable for shared hosting.

**Describe the solution you'd like**

The expressions you can generate in the "Basic" tab of the script editing panel (visibility/workflow scripts etc) is a safe subset which still allows for some useful configurations. So it would be good to limit scripts to this subset.

I propose an optional flag (in optional-config.properties) which: 
* Doesn't change anything at all if not set
* Checks scripts conform to the restrictions set in the "Basic" tab of the scripting dialog(s)
* Disables 
  * "Advanced" scripting tab
  * "Expert Scripting" tab on collection editor
  * "Advanced scripting" wizard control
  * "Scripted section" on display wizard
  * "Scripted" portlet
  * "Execute Script" bulk item action

It is not intended that an installation which already contains "unsafe" scripts should function in a friendly manner (exceptions will be displayed upon use of non-conforming scripts). This is a flag which would be set once upon installation and not changed.

**Comment by abidingotter** [comment]
Let's leave this issue open since there is already a PR for it
