### ISSUE TITLE
Investigate upgrading Apache Tika

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#1214]
Renovate Bot raised a PR (#1208) to update Apache Tika, however it had a whole lot of SBT merge deduplication errors. Possibly, it's a case of Tika's sub dependencies also being explicitly specified from when the migration to SBT was done - but would have to spend time looking.

But also note, when looking at this, previous attempts to update Tika also found other things getting broken: #909

**Comment by cbeach47** [comment]
Updating tika-core and `tika-parsers` to 1.23 still have the deduplication issues when running `sbt installerZip`, however `sbt compile` does work.  The deduplication issues look to center around the `org.apache.cxf` dependency of 2.7.6 in `equellaserver/build.sbt`.  Investigating the level of effort to upgrade cxf as well (which mostly affects SOAP).

**Comment by edalex-ian** [comment]
Interesting, as the tests unfortunately are using 3.3.x as can be seen in this recent PR update: https://github.com/openequella/openEQUELLA/pull/1325

Interesting that renovate bot does not appear to have ever picked up the one in `equellaserver/build.sbt`. I wonder if it's due to the `excludeAll` throwing out a pattern match or sommink. :thinking:

**Comment by cbeach47** [comment]
After some exploration:
- tika 1.23 pulls in the latest cxf 3.3.5.
- oEQ already uses cxf, but cxf 2.7.6 , thus the merge conflicts
- It'll compile, but on building it, sbt is unable to deduplicate cxf files 
- As per https://cxf.apache.org/docs/30-migration-guide.html , Spring 3.2 or newer is required when using CXF 3.X.  oEQ uses Spring 2.5.5
- Looking at https://docs.spring.io/spring/docs/upgrade/spring3/pdf/spring-framework-upgrade.pdf , it looks reasonable to upgrade to the latest Spring 3 (though I'm hesitant to jump more then one major version at a time) - seems like Spring3 will allow CXF and Tika to then be upgraded.  

Interested if folks know of any blockers in moving to Spring 3.

**Comment by edalex-ian** [comment]
Dang, that's a significant change. Things are definitely getting a bit more concerning, hopefully the regression tests can cover most of what this kind of change would do though.

One item that jumped out was the changes touching on Struts 1.x - which oEQ uses for the basis of Sections. Hopefully it'll be fine.

I find the use of Spring and Guice in the one code base interesting, so we'll have to see.

Let's see how the travis build for your commit goes.

**Comment by abidingotter** [comment]
@edalex-ian I'm pretty sure there is no use of struts in sections.  The URLs with .do suffix were maintained purely to preserve any existing links to pages.

**Comment by cbeach47** [comment]
Both builds failed.  Due to the widen scope of this effort, this'll probably need to wait for a future release.

**Comment by cbeach47** [comment]
Tika is now upgraded via a different ticket with Spring / Hibernate.  Closing issue.
