### ISSUE TITLE
Admin console banner does not fit inside window in the new launcher

### ISSUE THREAD

**Issue by abidingotter** [openequella/openEQUELLA#1221]
Due to some difference with Oracle Java vs OpenJDK java, the window size in the new launcher is smaller than it should be (I couldn't work out why) and so the banner no longer fits.

![image](https://user-images.githubusercontent.com/1694589/64393000-a4c9c500-d092-11e9-81f7-49450d349ddd.png)

**Comment by abidingotter** [comment]
The actual whole window is narrower in OpenJDK, despite the same call to setSize to set the width to 450pixels.  I have “fixed” the issue by making the window wider and resizing the header and footer images. (I also de-giffed them 🙂 )

![image](https://user-images.githubusercontent.com/1694589/64393028-e195bc00-d092-11e9-99c1-bd9d16f124ac.png)

**Comment by cathfitz** [comment]
Tested and looks good
