### ISSUE TITLE
Language pack for arabic not working

### ISSUE THREAD

**Issue by abdkhanEummena** [openequella/openEQUELLA#1235]
**Description**
I have managed to zip and upload an arabic Language pack from the Settings page. Also the users can now see the localized strings. See attached screenshots. But since my language pack is arabic the interface should also change accordingly and menu should appear in the right hand side. The documentation says openEquella handles languages that are written from right to left but in my case it doesnt work.

**To Reproduce**

1. Create a arabic language pack.
2. Zip it and upload it from the settings page while logged in as an Admin.
3. Login as a user and change the "Preferred display language" in the "My Preferences" page.
4. The strings will change but the menu stays on the left hand side.

**Expected behavior**
The menu should come on the right hand side.

**Screenshots**
![image](https://user-images.githubusercontent.com/53985295/64511184-5ff79580-d301-11e9-8396-37e9208b0ef1.png)

**Platform:**

- OpenEquella Version: [Installer built from the dev branch manually]
- OS: [Ubuntu 16.04]
- Browser [Firefox]

**Comment by edalex-ian** [comment]
Hey there @abdkhanEummena 

Does this only happen with the New UI turned on?

**Comment by abdkhanEummena** [comment]
Hi @edalex-ian ,

I tried with the old UI as well, same problem. Please see the screenshot.
![image](https://user-images.githubusercontent.com/53985295/64594849-6bfd5900-d3ce-11e9-9d7b-ed8f0465075d.png)

Regards

**Comment by edalex-ian** [comment]
That is curious, as I'd expect that to work. Are you able to attach your custom language pack?

**Comment by abdkhanEummena** [comment]
Yes I am able to upload my language pack and as a user I can also change the preferred language from the "My Preference" page. If you look at the dashboard ( see previously attached screenshot) you will see that instead of "Welcome to openEquella" I now have an Arabic text.

**Comment by edalex-ian** [comment]
Sorry for the confusion @abdkhanEummena . I was wondering if you're able to attach you custom language pack *here* in GitHub for us to have a look?

**Comment by abdkhanEummena** [comment]
@edalex-ian Its a very basic JUST-FOR-TESTING language pack.
[language-pack-ar_SA_ar.zip](https://github.com/openequella/openEQUELLA/files/3601060/language-pack-ar_SA_ar.zip)

**Comment by abdkhanEummena** [comment]
I hope you got the question! The problem is not with the localization itself but with the orientation of the openEquella after a **RIGHT-TO-LEFT written** language pack is activated. I am not sure if this is even handled in openEquella! So according to me if a **RIGHT-TO-LEFT written** language pack(_arabic in my case_) is activated, the complete menu should start appearing in the right hand side of the web page instead of the currently appearing left hand side. I hope i was able to make it clear. If you want to know anything else please do let me know. 

Regards.

**Comment by edalex-ian** [comment]
Ahhhh, thanks @abdkhanEummena , I did miss-understand your issue. I now understand it you're raising the issue of the placement of the menu. (Should be right in RTL configurations.)

I'm unsure if that's implemented in the new UI, but yes it should work in the old UI. However I had one of the team have a very quick look, and it seems the placement is also based on interrogating the locale, so you might want to check what you've got that set to.

**Comment by abidingotter** [comment]
Hi @abdkhanEummena 
I believe that the "new UI" probably hasn't been designed yet with that in mind.  If you switch to the old UI (Go to settings menu in openEquella) you should hopefully see the menu on the right hand side.  I know it used to work, but hopefully it hasn't regressed.

**Comment by abdkhanEummena** [comment]
@abidingotter I checked with the old UI as well, the menu stays on the left hand side even when the Arabic language pack is working. See this screenshot https://user-images.githubusercontent.com/53985295/64594849-6bfd5900-d3ce-11e9-9d7b-ed8f0465075d.png

**Comment by abdkhanEummena** [comment]
@abidingotter Any update on the same. Because the RTL thing is not working with Arabic language pack. Please look if the language pack in configured the right way. https://github.com/openequella/openEQUELLA/issues/1235#issuecomment-530385407

**Comment by abidingotter** [comment]
@abdkhanEummena I do remember that RTL was working in the old UI before.  It's possible it could have stopped working though.  
Do you have your browser configured to request Arabic? In Chrome, go to Settings, click Advanced, scroll down to Languages and make sure Arabic is added and is at the top of the list.

**Comment by abdkhanEummena** [comment]
I will surely confirm my browser the way you told me to and check if it works. Meanwhile can you please verify if my Arabic language pack is correct.

**Comment by abdkhanEummena** [comment]
The thing is not working even if the browser settings is configured as you said in your last comment.
Please see the screenshots of the settings page.
![image](https://user-images.githubusercontent.com/53985295/66096625-46fe9f00-e5a4-11e9-991a-00303395e238.png)

Also of the Dashboard in the old UI theme, which doesn't seem to have changed. If you see closely instead of "Welcome to Dashboard" its arabic variant has been picked. But the RTL doesn't work.
![image](https://user-images.githubusercontent.com/53985295/66096673-79a89780-e5a4-11e9-8ec9-b39808b66b9b.png)

Any help would be appreciated.

**Comment by mrblippy** [comment]
Hi @abdkhanEummena

Can you please try adding the following to the locale.properties file in your language pack?
**rtl=true**

Note that currently right to left only works in the old UI

**Comment by abdkhanEummena** [comment]
Hello @mrblippy 

Thanks for your help. That worked really well.
![image](https://user-images.githubusercontent.com/53985295/66251043-e1511500-e753-11e9-8138-a2a71ff1d5cb.png)


Any idea when the same functionality is going to be implemented in the new UI?
Please also point me to the src code where locale is being handled for the new UI.

Regards

**Comment by abdkhanEummena** [comment]
Thanks for all your support and help. I am closing this issue as RTL now works for me with the old UI.
