### ISSUE TITLE
Search text overwriting when typing in search text box for new Search UI

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#1239]
**Describe the bug**
When entering text in search text box in new Search UI, the characters get overridden unless you wait a second between typing each one

**To Reproduce**

1. Switch the new UI on
2. Switch the new Search UI on
3. Go to the search page and enter a search string
Note that each character overwrites the last one unless you type very slowly.

**Platform:**

- OpenEquella Version: [e.g. 2018.2, 2019.1]
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [Chrome, Firefox]

**Comment by edalex-ian** [comment]
Addressed by #1158
