### ISSUE TITLE
Cloud provider registration failing on first attempts when registering in a clustered environment

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#1240]
**Describe the bug**
When registering a cloud provider in openEQUELLA, you have to make 2 or 3 attempts before the registration is successful after entering your username and password in the registration form in a clustered environment. 

**To Reproduce**

1. Go to Cloud providers and register using the cloud provider URL
2. Enter the provided credentials on the registration form
3. Note that you get an error message for the first few attempts before it eventually works

**Expected behavior**
Should work first time.

**Platform:**

- OpenEquella Version: [2019.1]
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by edalex-ian** [comment]
Addressed by #1189
