### ISSUE TITLE
Ability to sort Taxonomy terms via REST API

### ISSUE THREAD

**Issue by abidingotter** [openequella/openEQUELLA#1311]
Related to #725 , you should be able to sort an arbitrary term's children via the REST API

The contract is:
```
/api/taxonomy/{uuid}/sortchildren?path={parentTermPath}
```
where the parentTermPath is optional.  If parentTermPath is not supplied the root terms of the taxonomy will be sorted.

**Comment by abidingotter** [comment]
@edalex-ian @cathfitz FYI

**Comment by edalex-ian** [comment]
Is this included as part of #1225 @abidingotter ?

**Comment by abidingotter** [comment]
@edalex-ian Yes, I added it for the purposes of the autotest
