### ISSUE TITLE
Update Jackson (XML) packages to v2.10.x

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#1317]
**Is your feature request related to a problem? Please describe.**

oEQ is currently stuck on Jackson 2.9.x due to issues with SBT deduplication - see #1289. However the current version is 2.10.x.

**Describe the solution you'd like**

Address deduplication issues and upgrade to latest Jackson libs.

**Comment by cbeach47** [comment]
Testing note:  run autotests against mssql server.
