### ISSUE TITLE
Unable to upload File 

### ISSUE THREAD

**Issue by abdkhanEummena** [openequella/openEQUELLA#1324]
Unable to upload a file 

1. Go to 'Contribute'
2. Click on 'Learning Resources'
3. Select 'Files, URLs, YoutTube'
4. Follow the process and Try to upload a file from your system.

**Expected behavior**
The file should be upload under the learning resource.

**Screenshots**
![select_a_file](https://user-images.githubusercontent.com/53985295/67617824-c4a67b00-f7ef-11e9-9c29-0f2857fb396f.png)
![file_upload_error](https://user-images.githubusercontent.com/53985295/67617833-e30c7680-f7ef-11e9-940a-dd0ddd044d19.png)

**Stacktrace**
`Blocked loading mixed active content “http://equella.dev.eummena.org/FG/api/content/ajax/access/ru…4311e8ad6e&pages.pg=0&event__=p0c11_dialog_fuh.uploadCommand`

**Platform:**
- OpenEquella Version: [Installer built from the dev branch manually]
- OS: [Ubuntu 16.04]
- Browser [Firefox]

The problem according to me is the **http** URL where the file upload request is directing to.  I am running **SSL** but the file upload call is directing to **http** instead of **https**.

**Comment by ChristianMurphy** [comment]
Thanks @abdkhanEummena!
Contributions to help resolve the issue are welcome.

---

Some pointers on how one could get started:

The title from the screenshot is here:

https://github.com/openequella/openEQUELLA/blob/6cbcdc3df9a67433fcb33a9fda8eaf24fb795688/Source/Plugins/Core/com.equella.core/resources/lang/i18n-resource-centre.properties#L2081

The component being displayed is here:

https://github.com/openequella/openEQUELLA/blob/085cf6370438178e1246da6c1f7de08343761eb2/Source/Plugins/Core/com.equella.core/resources/view/file/file-add.ftl#L10-L13

the scala code backing the component is here:

https://github.com/openequella/openEQUELLA/blob/7270fb074d3d2cfda28fc8ec0dab055c5499d753/Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/controls/universal/handlers/FileUploadHandlerNew.scala#L323-L350

The code getting the URL is here:

https://github.com/openequella/openEQUELLA/blob/c9941d45ef6f8e598521993b408ea7ffd843a36b/Source/Plugins/Core/com.equella.core/src/com/tle/web/sections/ajax/handler/AjaxGeneratorImpl.java#L164-L167

The code building the URL is here:

https://github.com/openequella/openEQUELLA/blob/649b9ef1a3c7a7a1ecc91c0337f0483e3689f135/Source/Plugins/Core/com.equella.core/scalasrc/com/tle/web/api/LegacyContentApi.scala#L289-L293

**Comment by abdkhanEummena** [comment]
Thanks @ChristianMurphy for the details. However I think i have configured SSL the wrong way. Can you please point me to some documentation for SSL configuration? That would be very helpful. I am suspecting my SSL is breaking somewhere because firefox also complains about the same
![image](https://user-images.githubusercontent.com/53985295/67623173-22a48400-f82b-11e9-8c87-82a6b9541d71.png)

**Comment by ChristianMurphy** [comment]
https://github.com/openequella/openequella.github.io/blob/9fe2bfc04ed8aaa0c1f7a901eed24d116d05cdb1/guides/InstallationAdminGuide.md#configure-openequella-with-ssl

https://github.com/openequella/openequella.github.io/blob/277effe2018cccb5747db550a58273214c3c4610/guides/ClusteringConfigurationGuide.md#to-configure-apache-as-load-balancer-and-ssl-terminator

**Comment by mrblippy** [comment]
Hi @abdkhanEummena 

Can you also try setting 'userService.useXForwardedFor = true' in <openequella>/learningedge-config/optional-config.properties and make sure the server in front of oEQ is passing through the `X-Forwarded-Proto` header

**Comment by nelson-edalex** [comment]
> Unable to upload a file
> 
> Steps to reproduce the behavior:
> 
>     1. Go to 'Contribute'
> 
>     2. Click on 'Learning Resources'
> 
>     3. Select 'Files, URLs, YoutTube'
> 
>     4. Follow the process and Try to upload a file from your system.
> 
> 
> **Expected behavior**
> The file should be upload under the learning resource.
> 
> **Screenshots**
> ![select_a_file](https://user-images.githubusercontent.com/53985295/67617824-c4a67b00-f7ef-11e9-9c29-0f2857fb396f.png)
> ![file_upload_error](https://user-images.githubusercontent.com/53985295/67617833-e30c7680-f7ef-11e9-940a-dd0ddd044d19.png)
> 
> **Stacktrace**
> `Blocked loading mixed active content “http://equella.dev.eummena.org/FG/api/content/ajax/access/ru…4311e8ad6e&pages.pg=0&event__=p0c11_dialog_fuh.uploadCommand`
> 
> **Platform:**
> 
>     * OpenEquella Version: [Installer built from the dev branch manually]
> 
>     * OS: [Ubuntu 16.04]
> 
>     * Browser [Firefox]
> 
> 
> The problem according to me is the **http** URL where the file upload request is directing to. I am running **SSL** but the file upload call is directing to **http** instead of **https**.

Hi @abdkhanEummena,

Please try the followings:
1. In optional-config.properties, set **userService.useXForwardedFor** to **true**
2. In your load balancer, add a HTTP request header setting **X-Forwarded-Proto** to **https**

This should do the trick.

**Comment by abdkhanEummena** [comment]
@mrblippy @nelson-edalex  Thanks for your reply. Apart from these changes do I also need to update 

```
configurationService.proxyHost = 
configurationService.proxyPort = 
configurationService.proxyUsername = 
configurationService.proxyPassword = 
#configurationService.proxyExceptions = 
```
these properties in **optional-config.properties**?

**Comment by nelson-edalex** [comment]
Hi @abdkhanEummena, you shouldn't need to touch that if your network doesn't have proxy.

**Comment by cathfitz** [comment]
Hi @abdkhanEummena,
Can you tell me if your problem is now sorted?

**Comment by abdkhanEummena** [comment]
I have tried setting userService.useXForwardedFor to true. But just that didn't work. I am waiting for my admin guys to update the X-Forwarded-Proto property. I will update this post as soon as there are any updates.

**Comment by mrblippy** [comment]
Yeah, you need both of those properties for it to work.

Hope it works out for you

**Comment by mrblippy** [comment]
We probably should add this to the documentation for the new ui

**Comment by abdkhanEummena** [comment]
The suggestion by @nelson-edalex fixed it up. Thanks all for your support.
