### ISSUE TITLE
Google search metatags - reference Oxford Brookes Research

### ISSUE THREAD

**Issue by NextEdServices** [openequella/openEQUELLA#1340]
The following information relates to the new UI/openEQUELLA. We understand that the new UI is not fully developed, however we´d like to share this on Github to help prioritize this issue.

It seems that (Google) search robots are not able to index openEQUELLA content in the new UI.

Feedback from Oxford Brookes:
"The 'page source' view of a record seems to show just javascript - again this might be intentional but I'm concerned what effect this has on Search Engine Optimization. Will Google index our pages as effectively when the page source looks like this on our updated Test system rather than its counterpart on our non-updated Production system? I'm guessing the <meta> tags I added to help Google index our resources don't have any effect if the page source doesn't include them."

Yes, I've used them just as I have in the old EQUELLA 6.4. This is what the user-guide says:
In the Pre-load Javascript section, you can use the ‘meta’ script object to add custom meta tags, for example:
meta.add("description", xml.get("/item/description"));
This will add a new description meta tag to the page with the content of the items /item/description field. Now when Google indexes your page it will use this meta tag for the description it shows to users.

And this is what I've got in the Pre-load Javascript section of the Research collection:
meta.add("citation_title", xml.get("/item/name"));
meta.add("description", xml.get("/item/description"));

Please reference Edalex Support Ticket Number #101101

**Comment by edalex-ian** [comment]
This has been completed and tested.

**Comment by cathfitz** [comment]
@NextEdServices NOTE: this was released in oEQ 2019.2.
