### ISSUE TITLE
Form data is not being proxied through using Cloud Provider SDK

### ISSUE THREAD

**Issue by edalex-tom** [openequella/openEQUELLA#1356]
**Describe the bug**
Using the openEQUELLA Cloud Provider SDK and an extension control that submits data via a HTTP POST, the form data (have tried a file and string) does not appear to be proxied through to the cloud provider endpoint.

**To Reproduce**

1. Register a cloud provider
2. Add an cloud provider control to a contribution item that supports submitting form data (e.g. file) through a HTTP POST
3. Submit the form data through the control
4. Request is proxied through openEQUELLA but the form data does not appear to be available in the cloud provider endpoint

**Expected behavior**
The request including form data is proxied through openEQUELLA and sent to the cloud provider endpoint

**Screenshots**
N/A

**Stacktrace**
Not available

**Platform:**

- OpenEquella Version: 2019.2
- OS: Ubuntu 18.04
- Browser: Chrome

**Comment by cathfitz** [comment]
Not going to be done
