### ISSUE TITLE
DELETE requests are not being proxied through using Cloud Provider SDK

### ISSUE THREAD

**Issue by edalex-tom** [openequella/openEQUELLA#1369]
**Describe the bug**
Using the openEQUELLA Cloud Provider SDK and an extension control that performs a HTTP DELETE request, the request does not appear to be proxied through to the cloud provider endpoint. 

**To Reproduce**

1. Register a cloud provider
2. Add an cloud provider control to a contribution item that supports performing a HTTP DELETE request to a cloud provider endpoint
3. Perform the delete operation
4. HTTP DELETE request is made to openEQUELLA but no traffic is received from cloud provider endpoint

**Expected behavior**
The request is proxed through openEQUELLA and sent to cloud provider endpoint

**Screenshots**
N/A

**Stacktrace**
Not available

**Platform:**

- OpenEquella Version: 2019.2
- OS: Ubuntu 18.04
- Browser: Chrome

**Additional context**
Viewing http traffic with Wireshark shows the request to openEQUELLA but no further traffic to the cloud provider endpoint.  Changing the cloud provider control to perform a GET or POST operation instead of a DELETE showed openEQUELLA proxying the request.

**Comment by edalex-ian** [comment]
@edalex-tom did you also say `UPDATE` didn't work?

**Comment by edalex-tom** [comment]
I've double checked the requests and the `DELETE` and `PUT` requests do not result in subsequent proxied requests to the cloud provider endpoint.
