### ISSUE TITLE
Reordering attachments with New UI results in a blank page

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#1394]
**Describe the bug**

When viewing an item, if you use the 'Reorder attachments' feature and click 'save' you end up on a blank page with a URL ending in `/undefined`.

**To Reproduce**

Steps to reproduce the behaviour:

Starting in an institution with the New UI enabled...

1. Go to an item with multiple attachments
2. Click on 'Reorder attachments'
3. Make a simple change in the order
4. Click 'save'
5. You will see the blank page and note the URL ending in `/undefined`

**Expected behavior**

After clicking save (say in the legacy UI) you return to the image view without any navigation changes (i.e. AJAX).

**Platform:**

- OpenEquella Version: 2019.1.2, 2019.2.0-RC
- OS: Linux
- Browser Firefox

**Additional context**

Be interesting to see if this is in < 2019.1.

**Comment by cathfitz** [comment]
This needs to be fixed
