### ISSUE TITLE
View Count feature: shows "0" on old content items after upgrade

### ISSUE THREAD

**Issue by NextEdServices** [openequella/openEQUELLA#1397]
It seems that for records created after the update it looks like <views> is being successfully added to the item and to each attachment.

Problem: while records created before the update it looks like <views> is being successfully added to the attachments, but not to the items (and re-saving / re-drafting isn't fixing it).

EQUELLA Version 2019.1

**Comment by cathfitz** [comment]
@NextEdServices There was an issue with this that was fixed in oEQ 2019.1.2 - see https://github.com/openequella/openEQUELLA/issues/1199
