### ISSUE TITLE
"Share" feature gives no feedback if mandatory fields are left empty

### ISSUE THREAD

**Issue by phette23** [openequella/openEQUELLA#1407]
**Describe the bug**

When you share an item, the "message"  field (and the "email" one, but that is more obvious) is mandatory but if you leave it blank the page refreshes and there's no indication that nothing has happened. There should be an error or alert noting that an email was not sent. The only way you can know that an email was sent is if you're familiar with the successful state (an "email sent" message appears up top) but if you've never done that then it's unclear if your form submission was successful or not.

**To Reproduce**

1. Find an item for which you have sharing privilege
2. Select *Share*
3. Enter a valid email but leave the message field blank
4. Select the *Send Email* button

**Expected behavior**

Ideally, the form will be validated before submission, a missing mandatory field will be found, and an alert presented to the user. Honestly, I think the message field could be optional, but if it is to be required then an alert would be useful.

**Platform:**

- OpenEquella Version: 6.5 (maybe this doesn't apply to stable, I haven't tested, feel free to close if it doesn't)

**Comment by cathfitz** [comment]
This problem doesn't occur in new UI, but is still a problem with old UI in 2019.2. Version 6.5 is not a supported version of oEQ.
