### ISSUE TITLE
Tie in build integration tests into the Docker build file

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1411]
**Is your feature request related to a problem? Please describe.**
Adopters need a way to do a custom build of the code, and run the build integration tests against that build in a controlled environment.

**Describe the solution you'd like**
Update `Dockerfile-openjdk` to include the 'autotests' that are run on releases.

**Comment by cbeach47** [comment]
Since all the autotest functionality is wired into Travis via https://github.com/openequella/openEQUELLA/blob/develop/.travis.yml , I would like to find a way to directly use the travis logic in the Docker file.  However, there doesn't look to be a clean way to do that.

That said, I plan to setup a new Docker file ( `Dockerfile-autotests` ) that will take as input an oEQ install file and will follow the travis logic to install oEQ and execute the autotests without travis.  It will also be beneficial to run the tests off of an upgrade file, but I don't think headless upgrades are possible at this time.

**Comment by edalex-ian** [comment]
I think this is still in train with @cbeach47 's #1428 PR.
