### ISSUE TITLE
GET  ​/taxonomy​/{uuid}​/term API route does not work

### ISSUE THREAD

**Issue by phette23** [openequella/openEQUELLA#1476]
**Describe the bug**
Requests to `GET ​/taxonomy​/{uuid}​/term?path=TERM` return a 200 response with no body, indicating that a term exists but not giving access to its UUID so no further operations can occur. For instance, this makes it difficult to nest child terms under existing terms when programmatically constructing a taxonomy.

**To Reproduce**

1. Create a taxonomy with a single term, e.g. "TERM"
2. Send a request to `GET ​/taxonomy​/{taxonomy uuid}​/term?path=TERM`
3. The response is an empty array `[]`
4. The response headers also don't contain the term's UUID anywhere

**Expected behavior**
A single result should be returned like:

```js
[
  {
    "term": "TERM",
    "fullTerm": "TERM",
    "uuid": "2ae3f425-b4aa-459d-933f-22f7a4b6683c",
    "index": 0,
    "readonly": false
  }
]
```

This is consistent with what happens when you send a request without a `path` parameter and receive a list of all the root terms complete with their UUIDs.

**Screenshots**

Here's the problem demonstrated in the apidocs.do tool:

No `path` parameters specified returns all the root-level terms, note the first one:
<img width="622" alt="Screen Shot 2020-02-10 at 17 08 28" src="https://user-images.githubusercontent.com/1024833/74204460-1b618480-4c28-11ea-9ba6-4522bc73a7d9.png">

Specifying the first term's `path` causes nothing useful to be returned:
<img width="617" alt="Screen Shot 2020-02-10 at 17 08 45" src="https://user-images.githubusercontent.com/1024833/74204453-16043a00-4c28-11ea-9247-93446117a7df.png">

**Platform:**

- OpenEquella Version: 2019.2
- OS: Ubuntu on the server

**Further details**
This gap in the APIs is problematic for me because I often try to add child terms before checking that they already exist. I'd like to write a method that tries to add a term and returns the newly created term so that children can be nested under it; if there's a pre-existing a term, I need to catch the 406 "duplicate sibling" error, then send the existing term. This bug means the existing term cannot be found because /api/taxonomy/{uuid}/term doesn't give access to UUIDs and /api/taxonomy/{uuid}/search doesn't return _any_ UUIDs in its results list (which seems like another bug? It mars the utility of the search results).

**Comment by cathfitz** [comment]
@abidingotter could you check if this code was affected with the taxonomy changes for 2019.2?

**Comment by abidingotter** [comment]
@cathfitz Hi Cath, it's working as intended.  No functionality was removed as a result of 2019.2 changes.  Possibly UUIDs not being returned was broken, but haven't had a chance to look into that.  (However, one of the tests inspects the UUID of a term, so it mustn't be broken on that endpoint at least)


@phette23 
Hi Eric, the term?path=X endpoint returns child terms of the given path, hence the empty array returned.  There doesn't seem to be any way of retrieving an individual term other than by its UUID.  I assume if you supply a path that doesn't exist you will get a 404 response instead of a 200?  Can you use that to determine if the term exists or not?  

I agree, the term UUIDs should be returned, and I can't see anything in the code preventing them being returned.  Will investigate tomorrow when I have an Equella instance to test against.

**Comment by phette23** [comment]
Thanks for the quick responses. I wasn't aware that path=X is meant to return child terms, that's not obvious from the way the API route is described.

> There doesn't seem to be any way of retrieving an individual term other than by its UUID. I assume if you supply a path that doesn't exist you will get a 404 response instead of a 200? Can you use that to determine if the term exists or not?

This is the crux of the matter; I want to find a term's UUID given its path, but that's not possible, I can only determine if it exists or not, which isn't good enough. For instance, unless I'm missing something, I can't nest a child term underneath it since I need to know it's UUID to supply in the parentUuid field.

Perhaps I've just misunderstood the purpose of this route though and the real solution is to have the /taxonomy/{uuid}/search route return UUIDs in its results.
