### ISSUE TITLE
Metadata values disappearing when xpath is used in multiple areas, but only displayed once

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1489]
With the following setup, if I select `A` and click 'save and continue', the value is no longer selected.

While intuitively this should work, there is a warning in the admin console when referencing the same metadata target from different pages.  See if there is a way to fix this, or if it's 'just the way oEQ works'.

```
Page 1
  Radio Button Group 1
    A - A
    B - B
Page 2 (with a scriptlet of `return false;`)
  Radio Button Group 2
    B - B
    C - C
    D - D
```

**Expected behavior**
The value `A` should stay selected.

**Environment**
- OpenEquella Version: 2020.1.0-Alpha
- OS: Linux
- Browser Firefox

**Comment by cathfitz** [comment]
@cbeach47 Nelson has unsuccessfully tried to replicate this in versions earlier than 2020.1 (we don't have access yet).

**Comment by cbeach47** [comment]
Hi @cathfitz , 2020.1.0-RC should be available within the next 24 hrs, however, I didn't confirm on a earlier version.  I'll put that on my list to see if I confirm Nelson's finding.

**Comment by cbeach47** [comment]
After further research, it breaks best practice to reuse metadata paths across pages, so while it may work in some cases, it's not recommended.
