### ISSUE TITLE
New UI: Reordering dashboard portlet not working

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1523]
**Describe the bug**
In the new ui dragging and dropping a dashboard portlet results in the user being redirected to a url ending in undefined. eg http://localhost:8020/vanilla/undefined

I'm thinking the callback that occurs when a portlet is dropped is not getting the url path properly in legacycontent. the path should end in home.do

A similar issue happens when [reordering attachments](https://github.com/openequella/openEQUELLA/issues/1394). The fix is likely to be the same

**To Reproduce**

1. Enable the new ui
2. Login to equella (using an actual user, not TLE_ADMINISTRATOR)
3. On the dashboard, click the three dot menu on the top right hand side
4. Add any portlet that tickles your fancy
5. Once the portlet has been added, click and drag it into a different position of the screen
6. Notice you are redirected to a url ending in 'undefined'

**Platform:**

- OpenEquella Version: 2019.2, 2020.1

**Comment by edalex-ian** [comment]
I see @cathfitz has this planned for 2020.2 and has removed the `stale` label, so I'm adding `Edalex` to ensure it doesn't go stale again.
