### ISSUE TITLE
New UI: Contribution - Right nav doesn't follow when scrolling down.

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1524]
**Describe the bug**
In the old ui the right hand navigation, (which contains all of the major wizard actions) used to stick to the top of the page while scrolling. 

![sticky](https://user-images.githubusercontent.com/4625498/76036857-6c4f6900-5f99-11ea-9e98-19469aee0b5b.gif)

In the new UI it no longer does this. It was an oversight by me when rewriting the css for legacy content :(

To fix this it should be as easy as adding the following css selector to the legacy.scss file:
```
.affix {
    position: fixed;
}
```

**To Reproduce**

1. Enable the new ui
2. Open up a contribution wizard that requires vertical scrolling 
3. Scroll down to the bottom of the page
4. Notice that the content on the right hand side isn't visible when scrolling to the bottom of the page

**Platform:**

- OpenEquella Version: 2019.2, 2020.1

**Comment by edalex-ian** [comment]
Another one that it looks like Edalex has done for 2020.2. So I'll add the Edalex tag so that it doesn't go stale again.

(Also, if this has been tested then it could be closed. @PenghaiZhang do you know if it's tested?)
