### ISSUE TITLE
New UI: Some contribution wizard controls are half width

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1527]
**Describe the bug**
I must've messed up some of the contribution wizard styling while I was rewriting the css for legacy content in the new ui. 
As a result of this some contribution wizard controls are not full width. Controls affected are: 
- Shuffle list
- Auto-complete taxonomy
- Grouping control

**Expected behavior**
All wizard controls should be the full width, just as they were when the New Ui is disabled.

**Screenshots**
![old v new](https://user-images.githubusercontent.com/4625498/76045349-e2ab9580-5fb0-11ea-8cfd-be2a2fa50f9f.jpeg)

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**

- OpenEquella Version: 2019.2, 2020.1
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [e.g. Chrome, Firefox]

**Comment by edalex-ian** [comment]
Adding Edalex tag, as it looks like we've worked on this and it will be in 2020.2.
