### ISSUE TITLE
Unable to troubleshoot what is being lost when message queue starts dropping messages

### ISSUE THREAD

**Issue by smclaughlin520** [openequella/openEQUELLA#153]
When Support sees messages in the logs like:
```
 MessageSender - Dropped 1 messages from queue for NODE: ...
```
 It's not clear what severity of an issue we're dealing with.
 
 I would find it helpful to have Equella log the contents of the message being dropped, and a hook to log what the current queue of messages are.

This might be a feature request, though I could see it being a bug to not have enough detailed logging. 

Issue Converted from original Equella JIRA

**Comment by cbeach47** [comment]
Any thoughts on how to replicate this manually?  Equella is a black box when this messaging occurs.  
- What is the message being dropped?
- See the head+10 messages and tail+10 messages of the queue (seeing the whole queue is millions of messages, and would be a performance hit to write out the contents to a log)?
- More of a general level - what could we design to have a better view into the health of a cluster, and even help fix the filled queue without restarting the Equella process?
