### ISSUE TITLE
New Ui: Structured Selection Session display issues

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#1540]
**Describe the bug**
The styling of the LMS course display in a Structured selection session got messed up at some point during the CSS rewrite of legacy content styling. Making it pretty unusable

![selection session display issues](https://user-images.githubusercontent.com/4625498/76716528-9caaba80-6784-11ea-9d10-921e66c8f9ab.PNG)

**To Reproduce**

1. Launch an oEQ Structured selection session from an lms (eg. moodle)
2. Notice the right hand column styling looks funky. It may even appear off screen

**Platform:**

- OpenEquella Version: 2019.2, 2020.1

**Additional context**
The column sizes in a selection session are also fixed width, meaning the selection session doesn't make good use of screen real estate. Especially if we implement [this fix in the moodle module](https://github.com/openequella/moodle-mod_openEQUELLA/issues/52)

**Comment by SammyIsConfused** [comment]
Verified, tested and fixed on develop.  Closing.
