### ISSUE TITLE
Full screen mode doesn't show content at certain zooms

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1569]
Viewing content in 'Full screen mode' will not display the content in the center pane on certain zoom levels.

**To Reproduce**

1. Create an item with several attachments, including PDF, JPG, and PNG
2. Click on 'Full Screen'
3. Click on one of the attachments
4. Select an attachment and zoom in / out until it does not display.

**Expected behavior**
The attachments should display at any zoom level.

**Screenshots**
Failing @ 120%:  
![image](https://user-images.githubusercontent.com/28629296/77377616-9ea2e980-6d41-11ea-9674-04e55c3b4c07.png)

Working @ 100%:
![image](https://user-images.githubusercontent.com/28629296/77377668-ca25d400-6d41-11ea-8644-9372a70cc047.png)

**Platform:**
- OpenEquella Version: 6.4-QA3, 2020.1.0
- OS: Ubuntu
- Browser: Firefox

**Comment by edalex-ian** [comment]
Confirmed. I'm seeing it start to happen at 140% on FF74 on Debian in 2020.1. But only when you have multiple items.
