### ISSUE TITLE
Unable to add a title for a URL on initial contribution

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1666]
**Describe the bug**
When adding a URL to an oEQ item, there used to be a field for URL title and URL.  In 2020.1.0, now there's only a field for URL.  To modify the URL title, the user has to edit the URL.

**Expected behavior**
On initial contribution, users should be able to specify a URL title/name, and the URL.

**Screenshots**
![image](https://user-images.githubusercontent.com/28629296/80511224-71011f80-8941-11ea-84ee-08e96be9c50f.png)

**Platform:**
- OpenEquella Version: 2020.1.0

**Comment by cbeach47** [comment]
@cathfitz Is this something that your team changed, or is it just a regression?  If it was on purpose to remove the field, was there a reason to not expose the functionality via a config in the collection definition editor?  Thanks!

**Comment by cathfitz** [comment]
@cbeach47 there was a change to the way the file uploader worked where it no longer showed the edit screen for files (back in 6.5 or 6.6) but not sure about this one? Do you know if it's happening in versions earlier than 2020.1?

**Comment by cbeach47** [comment]
@cathfitz - yes, it's happening in 2019.2.0 as well.

This doesn't seem to be part of the file uploader, and the title field is on the same page as the URL field, so the logic of omitting the edit screen on initial file upload.

Do you agree this wasn't an intended change?

**Comment by cathfitz** [comment]
@cbeach47 After further investigation I have discovered this was a purposeful change across all upload screens. The Edit option allows changes to attachment names across the board. I'm not saying it's a great change, but apparently it was a decision made.

**Comment by cbeach47** [comment]
Okay, thx for the details @cathfitz .

I'm going to leave this ticket open for the community as a 'request for change' for a configuration flag in the collection definition editor > Attachments widget to show the 'title' field for URLs.

**Comment by cbeach47** [comment]
After further review @cathfitz , I'm interested as to why the URL title field was removed on initial contribution?  

Was it to simplify the interface, or maybe something more fundamental to the attachment dialog pages?

Any known concerns to make the the loss of functionality configurable so adopters could 'turn it back on'? (currently thinking of making the field configurable per type of attachment)

**Comment by edalex-ian** [comment]
Some recent discussion around this in the dev mailing list: https://groups.google.com/a/apereo.org/g/equella-dev/c/3-T92tK3A3w/m/AaFKh0QZCQAJ

**Comment by edalex-ian** [comment]
@matjmiles did you still have an interest in this ticket?

**Comment by matjmiles** [comment]
Yes, I created a pull request and thought I had responded to all of the questions about it. This process is new to me so If I dropped the ball somewhere, let me know what I need to do.

I was under the impression that the pull request was still under review.

**Comment by edalex-ian** [comment]
> Yes, I created a pull request and thought I had responded to all of the questions about it. This process is new to me so If I dropped the ball somewhere, let me know what I need to do.

I think you're referring to PR #2295 which is just a doco one - which @SammyIsConfused is working to review. But this ticket is specifically about a feature which I think you mentioned you're having a student work on?

**Comment by matjmiles** [comment]
Oh yes, the student is working on the project right now and is hoping to have a pull request ready in the next week.
