### ISSUE TITLE
Blackboard selection session is broken in new UI

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#1725]
**Describe the bug**
The final call to ltireturn.do (generally Blackboard) in a selection session loses it's parameters, thus keeping the user in oEQ and not creating the LTI link in the calling LTI consumer (Blackboard).

**To Reproduce**

1. Setting an LTI Tool Provider for oEQ in Bb
2. In Blackboard, access the 'Build content' > oEQ LTI launch
3. Select a piece of content
4. Return the selection
5. Note how you get a relatively blank oEQ page and the link isn't created in Bb

**Expected behavior**
The link should be created in Bb and either the selection session should disappear or a notification appear that the link was created

**Screenshots**
![image](https://user-images.githubusercontent.com/28629296/81719373-9e21f780-9442-11ea-9d6f-830cb8a3ec73.png)

**Platform:**

- OpenEquella Version: 2020.1.0
- Browser: Confirmed in Chrome and Firefox

**Additional context**
Switching to the old UI allows the Bb selection session to work.

No errors are thrown in the logs

**Comment by edalex-ian** [comment]
Heya @cbeach47 

As per @SammyIsConfused 's comment over in the PR for Hotfix 2020.1.2 (#1738), we possibly have a fix in this which we needed to do for Canvas (#1744). If you're able to test against Bb that'd be great. :+1:

**Comment by cbeach47** [comment]
Cool, I'll take a look Tuesday / Wednesday of next week

**Comment by cbeach47** [comment]
Once the PR for Hotfix 2020.1.2 ( #1738 ) is complete and merged up into develop, this should be resolved.  Testing notes in the #1738 comments.  Leaving in 'Ready for Testing' until then.
