### ISSUE TITLE
Canvas integration issue with new UI

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#1744]
**Describe the bug**
There is a problem with the SelectOrAdd part of the new U/I.

Overview:  There are 3 points of integration.  The Course Navigation, Resource Selection, Editor Button.
Course navigation:  This is the Select Resources from openEQUELLA link in a canvas course left hand navigation.  It uses the structured integration endpoint.  This works in both old and new u/i.

The other two use the SelectOrAdd integration endpoint.  These work in the old U/I, but not in the new one.  In the new U/I, if you select a resource, you get a blank screen when trying to return the resource back to Canvas.

- OpenEquella Version: [e.g. 2020.1]
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by edalex-ian** [comment]
Possibly related to #1725.
