### ISSUE TITLE
Adding a favourite search gets 500 error returned

### ISSUE THREAD

**Issue by PenghaiZhang** [openequella/openEQUELLA#1750]
With New UI turned on, when add a favourite search through the dialog, pressing Enter to submit the request will result in 500 error whereas clicking the ADD button works fine.

1. Go to Search page, do a normal search and then click `Add search to favourites`
2. In the dialog,  press Enter to submit the request.
3. The page will display `500 : Internal Server Error`

**Expected behavior**
The message `Successfully added this search to your favourites` should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/47203811/82512113-7887a300-9b52-11ea-97f2-72f42cccc0f3.png)

**Stacktrace**
tbz6a12 00:31:17,091 ERROR [RestEasyExceptionMapper] REST API error
tbz6a12 java.lang.NullPointerException
tbz6a12 at com.tle.web.sections.js.generic.expression.FunctionCallExpression.getExpression(FunctionCallExpression.java:53)
tbz6a12 at com.tle.web.sections.js.generic.statement.FunctionCallStatement.getStatements(FunctionCallStatement.java:44)
tbz6a12 at com.tle.web.sections.js.generic.StatementHandler.getStatements(StatementHandler.java:74)
tbz6a12 at com.tle.web.sections.events.StandardRenderContext.bindHandler(StandardRenderContext.java:280)
tbz6a12 at com.tle.web.sections.SectionWriter.bindHandler(SectionWriter.java:499)
tbz6a12 at com.tle.web.sections.render.TagRenderer.processHandler(TagRenderer.java:348)
tbz6a12 at com.tle.web.sections.standard.renderers.AbstractComponentRenderer.processHandler(AbstractComponentRenderer.java:66)
tbz6a12 at com.tle.web.sections.standard.renderers.LinkRenderer.processHandler(LinkRenderer.java:88)
tbz6a12 at com.tle.web.sections.render.TagRenderer.processHandlers(TagRenderer.java:316)
tbz6a12 at com.tle.web.sections.render.TagRenderer.prepareAttributes(TagRenderer.java:297)
tbz6a12 at com.tle.web.sections.render.TagRenderer.realRender(TagRenderer.java:187)
tbz6a12 at com.tle.web.sections.standard.renderers.AbstractComponentRenderer.realRender(AbstractComponentRenderer.java:53)
tbz6a12 at com.tle.web.freemarker.methods.AbstractRenderDirective.execute(AbstractRenderDirective.java:83)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:389)
tbz6a12 at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.Macro$Context.runMacro(Macro.java:184)
tbz6a12 at freemarker.core.Environment.invoke(Environment.java:701)
tbz6a12 at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.MixedContent.accept(MixedContent.java:54)
tbz6a12 at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
tbz6a12 at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
tbz6a12 at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
tbz6a12 at freemarker.core.IteratorBlock$IterationContext.executeNestedBlockInner(IteratorBlock.java:240)
tbz6a12 at freemarker.core.IteratorBlock$IterationContext.executeNestedBlock(IteratorBlock.java:220)
tbz6a12 at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:194)
tbz6a12 at freemarker.core.Environment.visitIteratorBlock(Environment.java:572)
tbz6a12 at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:78)
tbz6a12 at freemarker.core.IteratorBlock.accept(IteratorBlock.java:64)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.MixedContent.accept(MixedContent.java:54)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.Macro$Context.runMacro(Macro.java:184)
tbz6a12 at freemarker.core.Environment.invoke(Environment.java:701)
tbz6a12 at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.MixedContent.accept(MixedContent.java:54)
tbz6a12 at freemarker.core.Environment.visitByHiddingParent(Environment.java:345)
tbz6a12 at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.MixedContent.accept(MixedContent.java:54)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
tbz6a12 at com.tle.web.sections.ajax.freemarker.AjaxCaptureDirective$BodyRenderer.realRender(AjaxCaptureDirective.java:156)
tbz6a12 at com.tle.web.sections.SectionWriter.render(SectionWriter.java:520)
tbz6a12 at com.tle.web.sections.render.TagRenderer.writeMiddle(TagRenderer.java:217)
tbz6a12 at com.tle.web.sections.render.TagRenderer.realRender(TagRenderer.java:189)
tbz6a12 at com.tle.web.sections.ajax.freemarker.AjaxCaptureDirective.execute(AjaxCaptureDirective.java:114)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:389)
tbz6a12 at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.MixedContent.accept(MixedContent.java:54)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.Environment.process(Environment.java:302)
tbz6a12 at com.tle.web.freemarker.AbstractFreemarkerFactory.render(AbstractFreemarkerFactory.java:57)
tbz6a12 at com.tle.web.freemarker.FreemarkerSectionResult.realRender(FreemarkerSectionResult.java:53)
tbz6a12 at com.tle.web.sections.render.CombinedRenderer.realRender(CombinedRenderer.java:56)
tbz6a12 at com.tle.web.sections.render.WrappedTemplateRenderable.realRender(WrappedTemplateRenderable.java:40)
tbz6a12 at com.tle.web.sections.render.CombinedTemplateResult$CombinedTemplateRenderable.realRender(CombinedTemplateResult.java:83)
tbz6a12 at com.tle.web.sections.render.FallbackTemplateResult$FallbackTemplateRenderable.realRender(FallbackTemplateResult.java:64)
tbz6a12 at com.tle.web.freemarker.methods.AbstractRenderDirective.execute(AbstractRenderDirective.java:83)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:389)
tbz6a12 at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.Macro$Context.runMacro(Macro.java:184)
tbz6a12 at freemarker.core.Environment.invoke(Environment.java:701)
tbz6a12 at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.MixedContent.accept(MixedContent.java:54)
tbz6a12 at freemarker.core.Environment.visit(Environment.java:324)
tbz6a12 at freemarker.core.Environment.process(Environment.java:302)
tbz6a12 at com.tle.web.freemarker.AbstractFreemarkerFactory.render(AbstractFreemarkerFactory.java:57)
tbz6a12 at com.tle.web.freemarker.FreemarkerSectionResult.realRender(FreemarkerSectionResult.java:53)
tbz6a12 at com.tle.web.sections.render.WrappedTemplateRenderable.realRender(WrappedTemplateRenderable.java:40)
tbz6a12 at com.tle.web.sections.render.FallbackTemplateResult$FallbackTemplateRenderable.realRender(FallbackTemplateResult.java:64)
tbz6a12 at com.tle.web.sections.SectionWriter.render(SectionWriter.java:520)
tbz6a12 at com.tle.web.sections.render.TagRenderer.writeMiddle(TagRenderer.java:217)
tbz6a12 at com.tle.web.sections.render.TagRenderer.realRender(TagRenderer.java:189)
tbz6a12 at com.tle.web.sections.SectionUtils.renderToWriter(SectionUtils.java:231)
tbz6a12 at com.tle.web.sections.SectionUtils.renderToString(SectionUtils.java:245)
tbz6a12 at com.tle.web.api.LegacyContentApi$LegacyResponseListener.returnResult(LegacyContentApi.scala:494)
tbz6a12 at com.tle.web.sections.events.RenderEvent.returnResult(RenderEvent.java:57)
tbz6a12 at com.tle.web.sections.render.HtmlRendererListener.render(HtmlRendererListener.java:48)
tbz6a12 at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:74)
tbz6a12 at com.tle.web.sections.events.RenderEvent.fire(RenderEvent.java:26)
tbz6a12 at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:471)
tbz6a12 at com.tle.web.sections.generic.DefaultSectionInfo.processEvent(DefaultSectionInfo.java:394)
tbz6a12 at com.tle.web.sections.registry.AbstractSectionsController.renderFromRoot(AbstractSectionsController.java:69)
tbz6a12 at com.tle.web.api.LegacyContentController$.super$renderFromRoot(LegacyContentApi.scala:237)
tbz6a12 at com.tle.web.api.LegacyContentController$.$anonfun$renderFromRoot$2(LegacyContentApi.scala:237)
tbz6a12 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
tbz6a12 at scala.Option.getOrElse(Option.scala:121)
tbz6a12 at com.tle.web.api.LegacyContentController$.renderFromRoot(LegacyContentApi.scala:237)
tbz6a12 at com.tle.web.sections.registry.AbstractSectionsController.renderForward(AbstractSectionsController.java:59)
tbz6a12 at com.tle.web.sections.registry.AbstractSectionsController.execute(AbstractSectionsController.java:45)
tbz6a12 at com.tle.web.api.LegacyContentApi.$anonfun$submit$1(LegacyContentApi.scala:450)
tbz6a12 at com.tle.web.api.LegacyContentApi.withTreePath(LegacyContentApi.scala:318)
tbz6a12 at com.tle.web.api.LegacyContentApi.submit(LegacyContentApi.scala:447)
tbz6a12 at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
tbz6a12 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tbz6a12 at java.lang.reflect.Method.invoke(Method.java:498)
tbz6a12 at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
tbz6a12 at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:511)
tbz6a12 at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:402)
tbz6a12 at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:366)
tbz6a12 at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)
tbz6a12 at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:368)
tbz6a12 at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:340)
tbz6a12 at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:313)
tbz6a12 at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:441)
tbz6a12 at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:231)
tbz6a12 at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:137)
tbz6a12 at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)
tbz6a12 at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:140)
tbz6a12 at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:217)
tbz6a12 at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
tbz6a12 at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
tbz6a12 at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
tbz6a12 at com.tle.web.remoting.resteasy.RestEasyServlet.service(RestEasyServlet.java:91)
tbz6a12 at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
tbz6a12 at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)
tbz6a12 at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)
tbz6a12 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
tbz6a12 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
tbz6a12 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
tbz6a12 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
tbz6a12 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
tbz6a12 at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
tbz6a12 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
tbz6a12 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
tbz6a12 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
tbz6a12 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
tbz6a12 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
tbz6a12 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
tbz6a12 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
tbz6a12 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
tbz6a12 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
tbz6a12 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
tbz6a12 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
tbz6a12 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
tbz6a12 at java.lang.Thread.run(Thread.java:748)

**Platform:**

- OpenEquella Version: [2020.1.1]
- OS: [Ubuntu 18.04]
- Browser [Chrome]

**Comment by SammyIsConfused** [comment]
This also happens when adding a URL attachment to a contribution. If you press enter in the dialog you get the same 500.
