### ISSUE TITLE
The REST endpoint '/api/search' does not find correct items with item status provided.

### ISSUE THREAD

**Issue by PenghaiZhang** [openequella/openEQUELLA#1783]
**Describe the bug**
When users do a search through ''/api/search'' and specify multiple item status, the result only includes items that is of the first item status.

**To Reproduce**

1. Open `apidocs.do` and go to `/search`;
2. Select `DRAFT` and `LIVE` in the item status list and then search;
3. The result only include items which are drafts. Live items are missing.

**Expected behavior**
The result should match what item status is provided.

**Screenshots**
![Screenshot from 2020-06-03 14-27-30](https://user-images.githubusercontent.com/47203811/83596140-3bd29780-a5a7-11ea-80bc-5087e29e84c1.png)

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**

- OpenEquella Version: [e.g. 6.5, 6.6]
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by cathfitz** [comment]
This will be fixed for 2020.2.
