### ISSUE TITLE
Allow openEQUELLA search results to be downloaded

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#1971]
**Is your feature request related to a problem? Please describe.**
A number of institutions have expressed the desire to be able to export/download a set of item search results

**Describe the solution you'd like**
An option from the new UI search page to save and/or download search results

**Describe alternatives you've considered**
Download to a CSV file after a search has been done

**Additional context**

**Comment by edalex-ian** [comment]
I see @cathfitz has raised this and it has a milestone. I'll add the `edalex` label to pin it.
