### ISSUE TITLE
REST API - Repeater Fields Search "AND" Issue

### ISSUE THREAD

**Issue by NextEdServices** [openequella/openEQUELLA#1995]
When using the API rest service to search for elements through the metadata we have a problem to filter when we have multiple metadata groups/repeater values.

For example, if we want to filter those metadata that have as metadata lomes/classification/purpose/value = "education level" and lomes/classification/taxonPath/taxon/id = 1 if we put the query where /xml/lomes/classification/purpose/value IS 'discipline' AND /xml/lomes/classification/taxonPath/taxon/id IS 1 gets us all those who meet that condition even if the taxon is in another classification.

For further context please see internal issue number zendesk #101356 

(Internal Ayesa reference number 2471)

**Comment by cathfitz** [comment]
@NextEdServices please be aware that most of the community do not have access to zendesk issues (including myself) so please make sure you include ALL details in this github issue.
