### ISSUE TITLE
Using the navigate back browser control doesn't close open dialogs

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#2251]
**Describe the bug**
In the New UI, if you open a legacy dialog and then navigate back, the dialog will remain open and interactive. In fact, you can still even upload and add attachments, which if you then reopen the same wizard will be present.

**To Reproduce**

1. Open a contribution wizard in a collection with an attachment control. 
2. Open the attachment dialog.
3. Either right click and use the back arrow function in the context menu, or the back button next to the URL bar in your browser.
4. If the navigation warning dialog is configured to appear (it happens whether or not it does) click "Discard Changes" .
5. Note that the navigation worked but the dialog remained open.

**Expected behavior**
Navigating away from the contribution wizard should close the dialog. 

**Screenshots**
![Peek 2020-09-02 11-55](https://user-images.githubusercontent.com/24543345/91923294-5259cd80-ed13-11ea-89d5-e17daeafc448.gif)

**Platform:**

- OpenEquella Version: 2020.1.3, 2020.2.0
- OS: Ubuntu 20.04.1 LTS (probably irrelevant)
- Browser: Firefox, Chrome (probably irrelevant)

**Comment by edalex-ian** [comment]
And just to clarify, this is only Legacy UI dialogs wrapped in New UI?

**Comment by SammyIsConfused** [comment]
> And just to clarify, this is only Legacy UI dialogs wrapped in New UI?
@edalex-ian That's correct, yeah. I'll make it more specific in the issue.
