### ISSUE TITLE
Settings menu not working in IE11

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#2285]
**Describe the bug**
The oEQ settings menu is being rendered using React, even when the old ui is being used. But, currently that settings accordion menu is not working at all when using IE11. There's just a blank space where it should be.
error in js console.

`SCRIPT1002: Syntax error
File: entrybuild.d8835b77.js, Line: 12811, Column: 164`

It looks to be blowing up because there is a => function contained inside the compiled js

![no settings ie11](https://user-images.githubusercontent.com/4625498/93274822-96160200-f7fe-11ea-8afc-7f32d73a1887.png)

**To Reproduce**

1. Ensure you have the New UI turned off
2. Navigate to the settings.do 
3. See error

**Expected behavior**
Settings menu should still work when using internet explorer when the old ui is enabled

**Platform:**

- OpenEquella Version: 2020.2
- OS: Windows 10
- Browser: Internet Explorer 11

**Comment by edalex-ian** [comment]
Ahhh, looks like we'll need to drop the ES target then. Pretty sure we bumped it recently thinking the New UI doesn't need to support IE11. But forgot about the settings page.....

**Comment by edalex-ian** [comment]
Ahhh, I think the culprit here is the `target` in `oeq-ts-rest-api/tsconfig.json`.

We're still aiming to support IE11 in legacy UI mode aren't we @cathfitz ?
