### ISSUE TITLE
Profile menu stays open when selecting the My preferences option so can't scroll until menu is closed

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#2303]
**Problem:**

When clicking on the profile icon in the top right, there's two options, Logout and My preferences. When you click My preferences, the Edit user page displays. I would expect I could immediately scroll down that page to find the setting I'm looking for, but because the Profile menu stays open, you need to click first on the page to close that menu before you can scroll.

![image](https://user-images.githubusercontent.com/32081370/93540993-ab269880-f998-11ea-83aa-5f1c9770f8ca.png)

**Solution**

Close menu once option selected

**Comment by edalex-ian** [comment]
Definitely in and working a charm. :+1:
