### ISSUE TITLE
REST API Internal Server Error for items with External LTI

### ISSUE THREAD

**Issue by scorpsteals** [openequella/openEQUELLA#2327]
**Describe the bug**
rest API /item/{uuid}/{version} throws an internal server error 500

**To Reproduce**
Upload an External LTI resource and submit the item. 
Retrieve the item via REST API 
/item/{uuid}/{version} throws an internal server error 500

**Expected behavior**
Item should be returned back

**Screenshots**
![image](https://user-images.githubusercontent.com/2992160/94292952-a4190080-ff2b-11ea-87b8-27d4405ad604.png)

**Platform:**

- OpenEquella Version:2020.1.3-Stable.OSE
- OS:  Windows 10
- Browser [ Chrome]

**Comment by edalex-ian** [comment]
Thanks for the issue report @scorpsteals 

Any chance you could also send us the relevant section from the server logs (Resource Centre logs)? I'd expect there'll be a ERROR with stacktrace at the time.

Also, which LMS is the external resource stored in?

**Comment by scorpsteals** [comment]
Yes. Here is the error in the server log and the external resource is in Moodle. The LTI link opens fine from the UI just fails from the REST API.


11:15:36,681 | bbbbea65-b51f-4dd6-be81-88faf9777975 | ERROR | RestEasyExceptionMapper | REST API error
-- | -- | -- | -- | --
java.lang.NullPointerException     at com.tle.core.externaltools.service.impl.ExternalToolsServiceImpl.customParamListToString(ExternalToolsServiceImpl.java:329)     at com.tle.core.externaltools.serializer.ExternalToolAttachmentSerializer.serialize(ExternalToolAttachmentSerializer.java:54)     at com.tle.core.item.serializer.impl.AttachmentSerializerProvider.serializeAttachment(AttachmentSerializerProvider.java:69)     at com.tle.core.item.serializer.impl.AttachmentSerializerProvider.writeItemBeanResult(AttachmentSerializerProvider.java:122)     at com.tle.core.item.serializer.impl.ItemSerializerServiceImpl$SimpleItemSerializerItemBean.writeItemBeanResult(ItemSerializerServiceImpl.java:415)     at com.tle.web.api.item.resource.impl.ItemResourceImpl.serializeOne(ItemResourceImpl.java:298)     at com.tle.web.api.item.resource.impl.ItemResourceImpl.singleItem(ItemResourceImpl.java:282)     at com.tle.web.api.item.resource.impl.ItemResourceImpl.getItem(ItemResourceImpl.java:140)     at com.tle.web.api.item.resource.impl.ItemResourceImpl.getItem(ItemResourceImpl.java:102)     at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)     at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)     at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:511)     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:402)     at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:366)     at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:368)     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:340)     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:313)     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:441)     at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:231)     at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:137)     at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)     at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:140)     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:217)     at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)     at com.tle.web.remoting.resteasy.RestEasyServlet.service(RestEasyServlet.java:91)     at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)     at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)     at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)     at java.lang.Thread.run(Thread.java:748)

**Comment by scorpsteals** [comment]
Similar error from an external LTI resource hosted on H5P:

10:17:45,576 | 4a7f92f7-3d45-418d-a2be-2c1249a87e16 | ERROR | RestEasyExceptionMapper | REST API error
-- | -- | -- | -- | --
java.lang.NullPointerException     at com.tle.core.externaltools.service.impl.ExternalToolsServiceImpl.customParamListToString(ExternalToolsServiceImpl.java:329)     at com.tle.core.externaltools.serializer.ExternalToolAttachmentSerializer.serialize(ExternalToolAttachmentSerializer.java:54)     at com.tle.core.item.serializer.impl.AttachmentSerializerProvider.serializeAttachment(AttachmentSerializerProvider.java:69)     at com.tle.core.item.serializer.impl.AttachmentSerializerProvider.writeItemBeanResult(AttachmentSerializerProvider.java:122)     at com.tle.core.item.serializer.impl.ItemSerializerServiceImpl$SimpleItemSerializerItemBean.writeItemBeanResult(ItemSerializerServiceImpl.java:415)     at com.tle.web.api.item.resource.impl.ItemResourceImpl.serializeOne(ItemResourceImpl.java:298)     at com.tle.web.api.item.resource.impl.ItemResourceImpl.singleItem(ItemResourceImpl.java:282)     at com.tle.web.api.item.resource.impl.ItemResourceImpl.getItem(ItemResourceImpl.java:140)     at com.tle.web.api.item.resource.impl.ItemResourceImpl.getItem(ItemResourceImpl.java:102)     at sun.reflect.GeneratedMethodAccessor215.invoke(Unknown Source)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)     at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)     at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:511)     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:402)     at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:366)     at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)     at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:368)     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:340)     at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:313)     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:441)     at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:231)     at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:137)     at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:361)     at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:140)     at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:217)     at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)     at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)     at com.tle.web.remoting.resteasy.RestEasyServlet.service(RestEasyServlet.java:91)     at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)     at com.tle.web.dispatcher.ServletDispatcher.dispatch(ServletDispatcher.java:95)     at com.tle.web.dispatcher.RequestDispatchFilter.doFilter(RequestDispatchFilter.java:91)     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)     at java.lang.Thread.run(Thread.java:748)
