### ISSUE TITLE
Check:md task intermittently fails on URL checking when the URL is fine

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#2360]
**Describe the bug**
A fair bit recently we've been having GHA build and check failures because of the check:md task. It would report the reason as being a bad URL, but checking the URL manually works fine.

**To Reproduce**
1. Create a branch with at least one commit on it and push it upstream so it builds. Every now and then during the build and check GHA task a random URL in one of the markdown files will fail the check:md task.
2. Open the link yourself, note that you are able to resolve the page as normal.

**Expected behavior**
There should be no false-positives for the check URL task. Now currently we have the -f option enabled which means "frail". What this does is exits with code 1 on warnings. Since no-dead-urls triggers a warning, we could potentially work around this by removing the -f option and letting the warning happen without failing the build. 

**Stacktrace**
```
> openequella@ check:md /home/runner/work/openEQUELLA/openEQUELLA
> remark -qf --ignore-pattern NOTICE.md .

README.md
  84:1-84:46  warning  Link to https://imagemagick.org/script/download.php is dead  no-dead-urls  remark-lint

⚠ 1 warning
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openequella@ check:md: `remark -qf --ignore-pattern NOTICE.md .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openequella@ check:md script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-10-01T18_09_26_401Z-debug.log
ERROR: "check:md" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openequella@ check: `run-s check:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openequella@ check script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-10-01T18_09_26_417Z-debug.log
Error: Process completed with exit code 1.
```

**Platform:**
- GitHub Actions

**Comment by edalex-ian** [comment]
Yup, it's tripping up dependency updates etc. It's probably just that we can't be 100% sure of various web server issues and interconnectivity from GHA build servers.

Let's remove the `-f`, and then in theory the warnings will pop-up in PRs anyway due to being a GHA annotation these days.

Are you able to action this @SammyIsConfused ?

**Comment by SammyIsConfused** [comment]
> Are you able to action this @SammyIsConfused ?

Sure thing! I'll have that up for PR today.

**Comment by SammyIsConfused** [comment]
So now that this is merged in, can this issue be closed?

**Comment by edalex-ian** [comment]
Sure can. :+1:
