### ISSUE TITLE
Support channels

### ISSUE THREAD

**Issue by stevegnz** [openequella/openEQUELLA#2493]
**Is your feature request related to a problem? Please describe.**
No support channel to ask about the issues I'm having

**Describe the solution you'd like**
http 403 errors when using proxy_http
adminconsole.jar not found from Linux_launcher.sh

**Describe alternatives you've considered**
Searched the internet and because you have no forum or support lines that would allow people who have common problems to discuss things this has to be one of the shonkiest outfits ever.

**Additional context**
Your documentation does not provide any sort of assistance whatever.

**Comment by edalex-ian** [comment]
Hi @stevegnz 

Please have a look over at the project's site at https://openequella.github.io/

You will note there you can find links to the community user "forum" under the 'Join the Community' section. But in case you still can't find it, here is a direct link: https://groups.google.com/a/apereo.org/g/equella-users

Alternatively if you want commercial support then a list of providers can be found on the project's page at the Apereo Foundation site under 'openEQUELLA Support'. (Here also is a direct link for that - although again, it can be found via the above link: https://www.apereo.org/projects/openequella .)

And lastly, there is the developer mailing list as per documented in the contributor guidelines for this repo. But again, for your convenience I provide the direct link: https://groups.google.com/a/apereo.org/g/equella-dev

Hopefully one of those several "support lines" can assist you with the information you're after. However if after that you still find there is a bug or you would like a feature enhancement, you're welcome to log it here.

Regards.
