### ISSUE TITLE
user_info_backup.username 'NOT NULL' constraint is dropped on upgrade

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#2499]
**Describe the bug**
`user_info_backup`.`username` `NOT NULL` constraint is dropped due to a migration between 2019.2.6 and 2020.1.4 (looks to be due to `RemoveLastKnownUserConstraint` not setting `nullable=false` on either username column in `FakeUserInfoBackup`.

An install for 2020.1.4 _has_ the `not null` constraint on that column.

**To Reproduce**
1. Install 2019.2.x
2. Check `user_info_backup` DDL
3. Upgrade to 2020.1.4
4. Compare DDL and note the constraint is dropped.

**Expected behavior**
Table DDL should be the same as an install to the same version (in this case, the DDL should not change)

**Additional context**

This has also been observed on the Spring-Hib-5 branch with Oracle and Postgres as well.  Have not run the specific test for SQL Server yet.

2019.2.6 DDL:
```
CREATE TABLE public.user_info_backup
(
  id bigint NOT NULL,
  email_address character varying(255),
  first_name character varying(255),
  institution_id bigint NOT NULL,
  last_name character varying(255),
  unique_id character varying(255) NOT NULL,
  username character varying(255) NOT NULL,
  CONSTRAINT user_info_backup_pkey PRIMARY KEY (id),
  CONSTRAINT user_info_backup_unique_id_institution_id_key UNIQUE (unique_id, institution_id)
)
```

Upgrade to 2020.1.4 DDL:
```
CREATE TABLE public.user_info_backup
(
  id bigint NOT NULL,
  email_address character varying(255),
  first_name character varying(255),
  institution_id bigint NOT NULL,
  last_name character varying(255),
  unique_id character varying(255) NOT NULL,
  username character varying(255),
  CONSTRAINT user_info_backup_pkey PRIMARY KEY (id),
  CONSTRAINT user_info_backup_unique_id_institution_id_key UNIQUE (unique_id, institution_id)
)
```

**Comment by edalex-ian** [comment]
@PenghaiZhang could you please comment on this. To me it sounds like it's working as you planned, but maybe I misread.

**Comment by cbeach47** [comment]
The issue imo is that there's a discrepancy between the DDL post upgrade (NOT NULL missing) and straight up install (NOT NULL absent).  Not sure which is the desired DDL.

**Comment by PenghaiZhang** [comment]
> The issue imo is that there's a discrepancy between the DDL post upgrade (NOT NULL missing) and straight up install (NOT NULL absent). Not sure which is the desired DDL.

Hi @cbeach47 , thanks for reporting this issue. I believe you are right, the cause is `FakeUserInfoBackup` does not have `nullable=false`. Can you please confirm if you straight up install 2020.1.4, `NOT NULL` is added ? 

In terms of which DDL is desired, I think we want `NOT NULL`.

**Comment by cbeach47** [comment]
> Can you please confirm if you straight up install 2020.1.4, NOT NULL is added ?
Sorry about the confusion, I mis-typed it earlier.  On a straight up install of 2020.1.4, `NOT NULL` is present.

**Comment by PenghaiZhang** [comment]
> @PenghaiZhang could you please comment on this. To me it sounds like it's working as you planned, but maybe I misread.

We have removed the unique constraint added on `username` but I think we need to keep `not null` on `username`.  I have asked Charlie if the username of a LDAP user can be `null` or not.  We both think we need `not null`.
