### ISSUE TITLE
Errant Tika warning with default config

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#2528]
The following gets logged on oEQ startup.  Annoying in the logs, but does not affect the functionality of tika parsing reasonable / expected files in oEQ.

```
WARN - TomcatLog - J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.

WARN - TomcatLog - org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
```

Looks like Tika is OK with the warnings since oEQ is using the default config.  Tika 2.0 looks like it may have logging flags so we can turn this warning off if we want via log4j:  https://issues.apache.org/jira/browse/TIKA-2518 and https://issues.apache.org/jira/browse/TIKA-2490

I did some reading up, and some of the warnings can be handled with more dependencies. Some may not be Apache v2 friendly. Since JPEG, TIFF, sqlite seems outside the range of supported oEQ parsable files for text indexing, I'm not excited to add in further deps to the build file just to silence errant warnings.  

The argument could be made to have oEQ support a tika config xml file which would allow this warning to be disabled.

This issue serves to document / raise awareness.

**Comment by edalex-ian** [comment]
I guess seeing image metadata is done via CLI tools currently it doesn't make sense to bring in extra deps - especially if they're not license compatible. So having an optional configuration option could be the goer - maybe no need for a dedicated file though (just some bools to turn on/off and then do what's needed programmatically).
