### ISSUE TITLE
Enable the module list to appear in the right hand Blackboard LTI selection session

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#2533]
**Is your feature request related to a problem? Please describe.**
With the modern Blackboard LTI integration , the course list no longer shows up on the right-hand side of the selection session. 

**Describe the solution you'd like**
This will require REST calls to the Bb site to build out the course list.

**Describe alternatives you've considered**
Blackboard doesn't send course lists with their LTI launches, thus the need for Bb REST calls.

**Comment by cathfitz** [comment]
@cbeach47 has testing been completed for this issue? Can it now be closed?

**Comment by cbeach47** [comment]
sry, yes
