### ISSUE TITLE
Convert GenLangStrings.purs to TypeScript

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#2558]
**Is your feature request related to a problem? Please describe.**

The community direction to remove Purescript from the project to assist with ongoing maintenance.

We need to convert the [GenLangStrings.purs](https://github.com/openequella/openEQUELLA/blob/develop/Source/Plugins/Core/com.equella.core/js/src/Tools/GenLangStrings.purs) from Purescript to TypeScript to assist with future maintenance.

**Describe the solution you'd like**

[GenLangStrings.purs](https://github.com/openequella/openEQUELLA/blob/develop/Source/Plugins/Core/com.equella.core/js/src/Tools/GenLangStrings.purs) is used as part of the NPM build process to generate a New UI language string bundle. This can be converted as a stand-alone activity.

Potentially the conversion result could sit at the top level of the JS tree in a directory such as `Source/Plugins/Core/com.equella.core/js/tools`. Following which, the its task would need to be updated, as would the call to use it as part of the build.

I propose this is done as part of 2021.1.

**Comment by edalex-ian** [comment]
@SammyIsConfused you've tested this one haven't you? Can it be closed?

**Comment by SammyIsConfused** [comment]
Tested. Closing.
