### ISSUE TITLE
Caching issues with Bb REST integration

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#2587]
**Describe the bug**
While the Bb LTI / REST integration functionally works, there are race and timeout conditions due to the caching that should be resolved.

**To Reproduce**
Primarily:
1. If the Bb token becomes expired partway through the flow, the behavior needs to be defined better.  
2. If the course or folder cache becomes expired partway through, the integration doesn't refresh the cache - it just fails.

**Expected behavior**

The token and user_id cache flows have well defined behavior if they are expire or are past their oEQ ttl partway through the flow.

The course and course_folder cache flows will pull data from Bb if the cache has no values available.

**Comment by cathfitz** [comment]
@cbeach47 Hi Chris. Is testing completed for this issue? Can we please close this ticket?

**Comment by cbeach47** [comment]
sry, yes
