### ISSUE TITLE
New UI - Registering Brightspace external connector fails with 500 error

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#2598]
**Describe the bug**
a 500 error is displayed upon registering a new Brightspace connector in the new ui, it appears to blow-up when trying to auto close the dialog.

If the dialog is closed manually (by clicking ok) the process completes successfully

![Peek 2020-12-14 13-31](https://user-images.githubusercontent.com/4625498/102033915-cf1b3e00-3e10-11eb-9d96-e288164b7617.gif)
note that the styling of the iframe looks a little bit busted, this capture was taken using 2020.1.6 It appears to have been rectified in 2020.2

**To Reproduce**

1. Ensure new ui is enabled
2. Go to Settings -> Integrations-> External system connectors.
3. Create a new Brightspace connector.
4. Enter Brightspace URL > Test URL > Enter ID and Key > Test Application.
5. Click `Sign in as a Brightspace administrator`.
6. Login in the pop-up and it returns an error.

**Expected behavior**
Once the administrator has signed into brightspace, the dialog should close successfully

**Platform:**

- OpenEquella Version: 2020.2, 2020.1, 2019.2, 2019.1, 2018.2

**Comment by edalex-ian** [comment]
@cathfitz if we plan to look at integrations in the future, do we want to schedule this one in?

**Comment by carl-edalex** [comment]
Bump.  This shouldn't have been closed.  It is still an issue with the new U/I and if OE is restarted, we have to go through the procedure of turning on the old UI, signing in, turn on the new UI in order to get Manage External Resources working again.

**Comment by edalex-ian** [comment]
Heya @snehanaik22 

When you tested Brightspace with 2021.2 did you have this issue?

**Comment by snehanaik22** [comment]
Yes. I was getting 500 error while testing 2021.2.
