### ISSUE TITLE
Canvas integration selection session doesn't close when selections have been made

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#2600]
**Describe the bug**
In Canvas integration, on Save the selection session doesn’t close, it stays open. 

This only occurs if there are selections made - without selections it simply closes the selection sessions when clicking Save and redirects back to the Canvas course page. Since there is a tooltip “x resource(s) added to Canvas” it seems that it was designed this way - potentially this was not possible in the Canvas integration? I have attached clips of this happening in the old and the new UI. It happens on stable as well, so 2020.1 is affected ( and probably older too).

**To Reproduce**

1. In a Canvas set up with oEQ integration, visit a course and click "Select resources from openEQUELLA". Wait for the selection session to open.
2. Once in the session, make some selections and click Save. 
3. Note that the selection session stays open, with a message confirming that the selections have been added to Canvas.
4. Save again, this time with nothing selected.
5. Note that the selection session closes and you are redirected to the Canvas course page.

**Expected behavior**
Once selections have been saved, the selection session should close and the user should be redirected to the Canvas course page. (I.E it should work the same as with other LMS selection sessions).

**Screenshots**
![Peek 2020-12-14 16-22](https://user-images.githubusercontent.com/24543345/102044067-27126e80-3e2a-11eb-9ad8-1b5abd9a6abb.gif)
![Peek 2020-12-14 16-18](https://user-images.githubusercontent.com/24543345/102044075-2974c880-3e2a-11eb-9f23-71b1deea535d.gif)

**Stacktrace**
No stacktrace for this issue, it fails to close silently (potentially because it was designed to work like this)

**Platform:**

- OpenEquella Version: Tested on 2020.1.6 and 2020.2 alpha. Potentially older. 
- OS: Ubuntu 2020.04.1 LTS
- Browser: Agnostic

**Additional context**

**Comment by cathfitz** [comment]
Designed this way
