### ISSUE TITLE
Attachment Preview does not support images contributed via Resource Selector in new Search UI

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#2617]
**Describe the bug**
Images contributed via the Resource Selector do not use the new Lightbox preview but instead launch into new tab. However the Old UI shows them with the normal fancy box setup.

This seems due to them having an attachment type of custom/resource rather than file .

**To Reproduce**

1. In the new search UI, go to a collection that has an oEQ resource selector and select some images
2. Save the item
3. Note that a thumbnail is not generated for the attachments

**Expected behavior**
Thumbnails are generated and dispaly on the search page

- OpenEquella Version: [2020.2 - New search UI]
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by SammyIsConfused** [comment]
Fixed.
