### ISSUE TITLE
EQUELLA did not throw error and return 500 to browser on Hikari errors

### ISSUE THREAD

**Issue by nelson-edalex** [openequella/openEQUELLA#264]
When there is an error with connection pool, e.g. unable to connect or not enough connection, EQUELLA will hold the HTTP request, keeping requesting Hikari for a connection infinitely and loop infinitely without timeout.

I tested this by:
1. Start up EQUELLA normally
2. Login to EQUELLA
3. Forcefully shutdown Postgres
4. Do a search
There is error logged in resource log, but nothing is returned to browser.

**Comment by alisherwani** [comment]
I am getting the same error, is there any solution for it

**Comment by alisherwani** [comment]
I solved this issue by increasing maximumPoolSize limit to 100 from 10 in Hikari setting file. 

file: /app/equella/learningedge-config/hikari.properties

#This property controls the maximum size that the pool is allowed to reach, including both idle and in-use connections. Basically this value will determine the maximum number of actual connections to the database backend. A reasonable value for this is best determined by your execution environment. When the pool reaches this size, and no idle connections are available, calls to getConnection() will block for up to connectionTimeout milliseconds before timing out. Default: 10

#maximumPoolSize = 10
maximumPoolSize = 100
