### ISSUE TITLE
MIME types can be configured such that they cause an error message in the new search UI

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#2707]
**Describe the bug**
If a MIME type entry is configured with a default viewer of File Viewer, but the Enabled checkbox for File Viewer is unchecked, then when an attachment of that MIME type turns up in a search on the new UI, an error snackbar appears at the bottom of the page labelled "Failed to get attachment viewer details: Missing viewer details for default viewer with id: "file"".

**To Reproduce**

1. As an admin, go to Settings -> General -> MIME Types.
2. Edit any MIME type entry or create a new one.
3. Scroll down to the Viewers section. Make the default radio button select File Viewer, and make sure the corresponding "Enabled" checkbox is unchecked. Save the MIME type.
4. If none exist, make a contribution that contains a file attachment of that MIME type.
5. Go to the search page and search for that item (it's likely already at the top of the page if you just added it)
6. Notice the error that displays at the bottom of the screen.

**Expected behavior**
There are a couple ways this could be fixed. We could make it so that if a MIME type is set to default then that option automatically checks Enabled and can't be unchecked without setting a new default. 

Or, we could handle this silently, such that if this configuration occurs it just uses a default viewer without displaying an error to the user, since most users wouldn't have MIME editing privileges and wouldn't be able to do anything about this.

**Screenshots**
![image](https://user-images.githubusercontent.com/24543345/106099106-4244fd80-618e-11eb-8550-4c6c6c5229da.png)
![image](https://user-images.githubusercontent.com/24543345/106099265-80422180-618e-11eb-93c7-cfafa37a6f79.png)

**Platform:**

- OpenEquella Version: 2020.2 onwards
- OS: Agnostic
- Browser: Agnostic

**Comment by snehanaik22** [comment]
Done Testing
