### ISSUE TITLE
Search Page : When changing page size, no need to scroll back to the top

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#2716]
**Is your feature request related to a problem? Please describe.**

On the new search page, when you change the page size the browser scrolls you back to the top of the window. However it'd be much easier if (like on other systems) you were able to continue scroll from where you were - i.e. the bottom of the page.

Video demonstration (oEQ version - 2020.2):

https://user-images.githubusercontent.com/43919233/106674765-ff5cad00-6607-11eb-8f9d-68ca60642385.mp4

**Describe the solution you'd like**

AS A user I WANT to search results page to stay where it is when the page size is changed SO THAT I don't have to scroll through content I've already scrolled through before.

**Additional context**

This was highlighted in the work being done in #2713 and as a result should be done after that is merged in. Once that is merged in, it will also required that the previous search results are kept displayed when changing page size.

**Comment by cathfitz** [comment]
Done and tested
