### ISSUE TITLE
New search UI doesn't have error handling in Selection Session 

### ISSUE THREAD

**Issue by PenghaiZhang** [openequella/openEQUELLA#2725]
**Describe the bug**
In the context of Selection Session, new search UI does not have any real error handling due to the implementation of `updateTemplate` being a `nop`. More details can be found in `App.tsx`,

**To Reproduce**

1. Open new search UI in Selection Session
2. Manually throw an error
3. Nothing is given to indicate an error has happened.

**Expected behavior**
An indicator like a `SnackBar` should pop up to let users know what error just happened.

**Screenshots**
N/A

**Stacktrace**
N/A

**Platform:**

- OpenEquella Version: 2020.2
- OS: Ubuntu 18.04
- Browser: Chrome, Firefox

**Additional context**
N/A

**Comment by snehanaik22** [comment]
Tested.
