### ISSUE TITLE
Failed to install openEQUELLA using the equella-installer-2020.2.0

### ISSUE THREAD

**Issue by tsnouidui** [openequella/openEQUELLA#2772]
**Bug Description**
I am having some difficulties completing the installation of openEQUELLa on my local machine
The installation failed at the Database Authentication step.

I have installed PostgreSQL and made sure that port 5432 is open so PostGreSQL can use it.
However when I run the installer of openEQUELLA, I get the following 

equella-installer-2020.2.0
![image](https://user-images.githubusercontent.com/3789840/109458520-04c5df80-7a6e-11eb-89b5-25b510c5c627.png)

**Platform:**

- OpenEquella Version: 2020.2.0
- OS: Windows 10
- Chrome
- PostGreSQL  version 13.2

Please note that I am completely sure about providing the installer with the correct credentials for the database. 
The connection script seems to be returning right away with the message shown in the screenshot.

**Comment by edalex-ian** [comment]
Hi There @tsnouidui 

I'm not currently aware of anyone having used the latest version of Postgres with openEQUELLA. Personally, the latest version I know to work is 11.8. Are you in a position to try a slightly older version for now?

If that turns out to be fine, then it looks like we'll need to raise a bug to add support for 13.x (not to mention maybe 12).

**Comment by tsnouidui** [comment]
Thanks for the feedback!

I have installed version 10 and was getting the same problem. After checking it turns out that the problem was because I hadn't granted the user database user equellauser permissions to log in. This I think need to be added to the instructions.

On another note, I have installed ImageMagick 7.0.xxx but when I try to install openEQUELLa it fails to validate the ImageMacgick's folder and complains that the directory doesn't contain the program `convert`.
Looking at the directory I could indeed see that the program `convert` was not present there.
Did you test the current installation with the latest version of ImageMagick (`ImageMagick-7.0.11-1-Q16-HDRI-x64-dll.exe`) ?

**Comment by tsnouidui** [comment]
The problem seems to be in the version of ImageMagick used. Version 6.9.xxx includes `convert.exe` whereas version 7.0.xxx doesn't include it. The code should use an alternative method to check if ImageMagick is installed.

**Comment by edalex-ian** [comment]
Thanks for persisting @tsnouidui :+1: 

So when you did figure out the access issues, did you end up still using PSQL 13 (or stayed with 10)?

Also yes, you're correct, we currently only know to work with IM 9.6. We're bit by bit trying to work up a list of supported software here: https://openequella.github.io/server-administration/KnownWorkingSupportingSoftware.html

If you do have any suggestions for the doco, we definitely welcome contributions over in the doco repo at https://github.com/openequella/openequella.github.io - whether that be a pull request, or raising an issue capturing what should be updated/added.

**Comment by tsnouidui** [comment]
I ended up using 10 but I am pretty sure that it will work with 13 as well since it was exhibiting the same behavior.

Well noted for the contributions/suggestions.

**Comment by edalex-ian** [comment]
No worries, thank you. Looks like this issue is all done, will close. But any further issues, please don't hesitate to let us know.
