### ISSUE TITLE
Batch import of one or multiple items

### ISSUE THREAD

**Issue by tsnouidui** [openequella/openEQUELLA#2782]
Is there a way to import one item or an entire collection with items at once?
This could be the case where one may have a lot of articles under a collection that one would like to import.

If there is any possibility or utilities that could automate the process of importing one or multiple items into the repository, then please let me know.

**Comment by edalex-ian** [comment]
Heya @tsnouidui 

For questions on usage etc I'd probably recommend hitting the users mailing list @ https://groups.google.com/a/apereo.org/g/equella-users as you'll hit a broader group (not just developers).

But that said, there are a couple of utilities for doing batch imports and modification, they are:

* EBI: https://github.com/openequella/openEQUELLA-ebi
* EMU: https://github.com/openequella/openEQUELLA-emu

Hope that helps.

**Comment by tsnouidui** [comment]
Thanks. I have joined the google group now.

**Comment by edalex-ian** [comment]
Excellent, I'll close this ticket off then. :+1:
