### ISSUE TITLE
Replace `:masterIssue` with `:dependencyDashboard` in `renovate.json`

### ISSUE THREAD

**Issue by HonkingGoose** [openequella/openEQUELLA#2899]
**Describe the bug**

Renovate bot does not use `:masterIssue` anymore, it's now called `:dependencyDashboard`.

**To Reproduce**

https://github.com/openequella/openEQUELLA/blob/b366c33254afa4d59e508c8e42a712045fbd407b/renovate.json#L2

**Expected behavior**

- `:masterIssue` is replaced by `:dependencyDashboard`

**Screenshots**

Not needed.

**Stacktrace**

Not needed.

**Platform:**

Does not matter, problem with source files.

**Additional context**

Renovate bot no longer uses the term Master Issue anywhere, this concept is now called the "Dependency Dashboard".
The preset was also renamed.

There's no "bug" as Renovate bot migrates old terms behind the scenes, but it's still better to use current terms, that way if you ever need to search the docs, you can find the relevant explanations easily.

Renovate docs for the "new" dependencyDashboard preset: https://docs.renovatebot.com/presets-default/#dependencydashboard

**Comment by ChristianMurphy** [comment]
Thanks @HonkingGoose! :bow: 
Opened #2900 to address this, any other deprecated properties you see?
Or other improvements that could be made to the configuration?

**Comment by edalex-ian** [comment]
Thank you muchly @HonkingGoose , great to have your advice.

We definitely appreciate the value your tool brings to our project, and we also know that our adopters greatly value the increased activity around having up to date dependencies. Thanks!
