### ISSUE TITLE
Update more outdated terms in `renovate.json` config file

### ISSUE THREAD

**Issue by HonkingGoose** [openequella/openEQUELLA#2902]
**Describe the bug**

I found some more outdated terms in your `renovate.json` config file. 😉 

**To Reproduce**

1. Go to https://github.com/openequella/openEQUELLA/blob/develop/renovate.json
1. Search for old terms `packageNames` and `packagePatterns`

These old terms been replaced with more descriptive terms which have the "prefix" `match` in them.
The capitalization of the term has changed as well. 😉 

**Expected behavior**

Replace:

- `packageNames` -> `matchPackageNames`
- `packagePatterns` -> `matchPackagePatterns`

**Screenshots**
Not relevant.

**Stacktrace**
Not relevant.

**Platform:**
Not relevant.

**Additional context**

Renovate bot documentation for the newer terms:

- https://docs.renovatebot.com/configuration-options/#matchpackagepatterns
- https://docs.renovatebot.com/configuration-options/#matchpackagenames

**Comment by edalex-ian** [comment]
Thank you @HonkingGoose . I've setup a PR for it.

Cheers. :+1:

**Comment by HonkingGoose** [comment]
Closing this issue, as it's fixed by PR #2906.
