### ISSUE TITLE
display openEQUELLA language preferences on navigation

### ISSUE THREAD

**Issue by miraboureslan** [openequella/openEQUELLA#2916]
how to add a language switcher on the navigation bar for all pages?
so that a user can change his language preference from any page rather than from my preferences page only

if this can be done by api  scripting please i need some help with this

**Comment by SammyIsConfused** [comment]
Hi miraboureslan, 
As far as I know, there is no way to directly do this. No endpoint directly controls the language setting for a given user. If you wanted to create a navigation bar link to the User Preferences page you could by going to Settings -> General -> Custom Links and creating one for {Your institution URL goes here}/user.do. You can control whom sees this link. 
![image](https://user-images.githubusercontent.com/24543345/116172517-457c6500-a74e-11eb-9ab3-85f2a18f330a.png)

**Comment by cathfitz** [comment]
Closing. No action required.
