### ISSUE TITLE
New Video Gallery: YouTube preview pane in video lightbox defaults and reverts to small - have to refresh to fix

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#2934]
**Describe the bug**
Currently, when you first go into Video mode and click on a YouTube video, the preview pane is very small. Doing a Ctrl/F5 makes it revert to the normal size. But if you do something in between (like open a Summary page) it reverts back to the small size.

**To Reproduce**

1. Go to Search page
2. Go to video mode
3. Click on a YouTube video
4. Note that it's small
5. Close the preview pane
6. Refresh (Ctrl/F5)
7. Reopen the preview pane for the YouTube video - note it's the proper size.
8. Close preview pane then open the Resource summary page for a video. 
9. Use the back button or click the Search menu
10. Preview another YouTube video - it's reverted back to being small again.

**Expected behavior**
The video preview should always show in the larger box

**Screenshots**
Small
![image](https://user-images.githubusercontent.com/32081370/116506656-0b06f980-a901-11eb-8070-b35388912194.png)
Correct size
![image](https://user-images.githubusercontent.com/32081370/116506680-14906180-a901-11eb-8a9e-80874b49be51.png)

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**

- OpenEquella Version: [e.g. 2021.1]
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by snehanaik22** [comment]
Tested.

**Comment by snehanaik22** [comment]
closed by mistake.

**Comment by snehanaik22** [comment]
Tested.
