### ISSUE TITLE
New search UI: MIME type filters set on Standard mode search screen carrying over to Video mode

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#2936]
**Describe the bug**
If someone sets the MIME type filter from the Standard search mode screen, it remembers the filter when changing to video mode (showing only videos for attachments that also have attachments with the set MIME types).

**To Reproduce**
1. From the Standard mode, set a MIME type filter (e.g. pdf)
2. Go to video mode
3. Note that only videos from items which also have pdf attachments display

**Expected behavior**
The filter should be cleared when moving to the video mode.

**Platform:**

- OpenEquella Version: [2021.1 new Search UI]
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by snehanaik22** [comment]
Tested.
