### ISSUE TITLE
Inline file uploads: dont work correctly in Edge browsers

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#295]
You only seem to be able to drag and drop files onto the "Click to select files or drag and drop files here" text, but not onto the rest of the drop target. Works as intended on firefox, chrome and IE11

**Comment by doolse** [comment]
Appears that it was a bug in Edge which has been fixed now

**Comment by mrblippy** [comment]
It's started happening again :(

**Comment by abidingotter** [comment]
Can't reproduce the issue ( Microsoft Edge 40.15063.674.0 )
