### ISSUE TITLE
Image gallery not available to users without EDIT_SYSTEM_SETTINGS permissions

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#2951]
**Describe the bug**
Users without EDIT_SYSTEM_SETTINGS permissions cannot access the Image mode in the new UI.

**To Reproduce**

1. Go to the new Search UI page (logged in as a non-admin with no EDIT_SYSTEM_SETTINGS permissions
2. Click on Image mode
3. Note the error

**Expected behavior**
Should display images
**Screenshots**
![image](https://user-images.githubusercontent.com/32081370/117087127-efcd3b80-ad91-11eb-850b-0506d55669ec.png)

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**

- OpenEquella Version: [2021.1]
- OS: [e.g. Windows 10, MacOS 10.13]
- Browser [all]

**Comment by snehanaik22** [comment]
tested
