### ISSUE TITLE
Fail to import audit logs

### ISSUE THREAD

**Issue by PenghaiZhang** [openequella/openEQUELLA#2960]
**Describe the bug**
Audit logs exported after 2018.2 cannot be imported back.

**To Reproduce**
1. Export an institution which has some audit logs.
2. Delete this institution.
3. Import this institution back.
4. Open table `audit_log_entry` and check if audit logs of this institution are missing. Or, export the institution again and check if any audit log is exported.

**Expected behavior**
All audit logs should be imported back.

**Screenshots**
N/A

**Stacktrace**
N/A

**Platform:**

- OpenEquella Version: [2018.2 onwards]
- OS: [Ubuntu 18.04]
- Browser [Chrome]

**Comment by edalex-ian** [comment]
I see @cathfitz has added this to 2021.2 so adding Edalex label to stop it going stale.

**Comment by edalex-yinzi** [comment]
Already fixed in 2021.2.0. See details in #2972.
