### ISSUE TITLE
Apply the settings that allow admins to hide the image and video gallery options to apply to the new Search UI page

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#2963]
**Is your feature request related to a problem? Please describe.**
Currently the options to hide Image and Video gallery modes on new Search UI page are not functioning. 
**Describe the solution you'd like**
If either/both options are set to not show the image/video mode options, then they should not show.

![image](https://user-images.githubusercontent.com/32081370/117256448-0e186180-ae8e-11eb-910f-2a4ade104fad.png)

**Comment by snehanaik22** [comment]
Done
