### ISSUE TITLE
New UI - Contributions from selection session cut off the save panel

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#2969]
**Describe the bug**
When in a selection session, if you start a contribution wizard, the save panel will have the rightmost part cut off. Scrolling to the right doesn't fix the issue.

**To Reproduce**

1. Start a structured selection session (e.g from Moodle)
2. Click on Contribute and start a contribution wizard
3. Note that the Save panel on the right is partially hidden.

**Expected behavior**
You should be able to view the whole save panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/24543345/117384010-59318380-af25-11eb-8618-2a72dcfa35e4.png)

**Platform:**

- OpenEquella Version: Found in 2021.1 - have heard this also happens in 2020.2
- OS: Agnostic
- Browser: Agnostic

**Comment by SammyIsConfused** [comment]
```css 
#selection-content-inner.wizard-layout .mainCols {
	flex-grow: 0.95;
}
```
This snippet of CSS seems to fix the issue.

**Comment by SammyIsConfused** [comment]
![image](https://user-images.githubusercontent.com/24543345/132268738-73a9b17c-f917-4b5e-88af-eca0e4310b25.png)
This issue still occurs, however my suggested fix no longer seems to work for some reason. 
Potentially worth fixing, or could wait until new UI resource summary focus.

**Comment by snehanaik22** [comment]
Tested.
