### ISSUE TITLE
Black line appears in DRM page in EBP UI

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#2970]
**Describe the bug**
When in a DRM enabled collection that you have not accepted the terms for, in the new UI with new search turned off, a black bar appears across the previous and next buttons. 

**To Reproduce**

1. Turn on the new UI, but turn off the new search page.
2. As a user that hasn't accepted the DRM (for a collection that requires accepting before viewing the item summary), visit the item summary, which should open a DRM terms of use accept dialog.
3. Note the black horizontal rule across the previous and next buttons.

**Expected behavior**
The black bar should not appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/24543345/117392023-8c2f4380-af34-11eb-9a16-92cf97f863e3.png)

**Platform:**

- OpenEquella Version: 2021.1
- OS: Agnostic
- Browser: Agnostic

**Comment by SammyIsConfused** [comment]
```
.itemsummary-layout #col2 hr { 
        display: none;
        }
```

This snippet of CSS seems to fix the issue.

**Comment by SammyIsConfused** [comment]
![image](https://user-images.githubusercontent.com/24543345/132268403-951dbd75-d56c-4309-a38e-6d79a81f3816.png)
This still happens on the head of develop, and the fix still works too. 
Very minor graphical issue, but considering the fix commented above still works, potentially worth fixing.

**Comment by snehanaik22** [comment]
Performed test and verified black line is not appearing for DRM page in EBP UI.
