### ISSUE TITLE
htmleditor.css missing from legacy.scss imports, stopping users from exiting full screen HTML editor control

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#3018]
**Describe the bug**
In the new UI, there are style rules missing from the old TinyMCE editor, which means that exiting fullscreen view is impossible without refreshing. 

In the old UI this works as intended - the "Toggle full-screen" link appears in the HTML editor.

**To Reproduce**

1. Start a contribution wizard for a collection that contains an attachment control for Web Pages.
2. Click on "Toggle full-screen"
3. Note  that you cannot exit fullscreen without refreshing, wiping your changes to the HTML editor.
4. Also note that you cannot exit fullscreen with the keyboard, E.G Alt+Enter or Esc.

**Expected behavior**
You should be able to exit fullscreen by clicking the button, like is possible in the old UI. 

**Screenshots**
new UI:

https://user-images.githubusercontent.com/24543345/119067471-89991780-ba25-11eb-9d7d-57a2aadefbcb.mp4

old UI:

https://user-images.githubusercontent.com/24543345/119067555-bcdba680-ba25-11eb-9c04-9c4fba885fdd.mp4

**Platform:**

- OpenEquella Version: 2021+
- OS: Agnostic
- Browser : Agnostic

**Additional context**
This is because there is a missing imported CSS file from our legacy.scss. The old UI contains a file called htmleditor.css - this should be included as an import to our legacy.scss.

**Comment by edalex-ian** [comment]
Has this been tested @snehanaik22 ?

**Comment by snehanaik22** [comment]
I haven't tested.

**Comment by snehanaik22** [comment]
Performed test when contributing an attachment control for Web Pages and  able to view Toggle full-screen button for exiting full screen mode in New UI

**Comment by snehanaik22** [comment]
done
