### ISSUE TITLE
Meta tags added repeatedly in new UI until browser crashes

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#3345]
**Describe the bug**
In the new UI if you have a collection with a Resource Summary Display Template that contains preloaded JavaScript that adds meta tags, this will loop infinitely rather than just once.  I can confirm that in 2020.2 this was working fine, but in later versions it adds the meta tag repeatedly until it consumes all browser resources. 

**To Reproduce**

1. Create a collection which contains a `meta.add` line in the Pre-load JavaScript section. 
2. Create an item with that collection and save it. 
3. Visit the resource summary and open your inspector. Go to the head tag and watch the number of metatags rapidly increase without stopping.
5. Note: this will keep happening until browser crash and your machine slows down. 

**Expected behavior**
Meta tags should be added only once (as happens in the old UI and pre 2021.1 new UI)

**Screenshots**
This is the head tag of a resource summary containing a meta.add, that has added thousands of meta nodes. 

![image](https://user-images.githubusercontent.com/24543345/130904710-cba2a8eb-1a91-4479-ad3e-2f957aa3ddf3.png)

**Platform:**

- OpenEquella Version: 2021.1+
- OS: Agnostic
- Browser: Agnostic

**Comment by snehanaik22** [comment]
Tested in new UI and meta tags are added only once and browser is not getting crashed.

**Comment by snehanaik22** [comment]
Tested.
