### ISSUE TITLE
Bb Selection session in new UI prevents selection

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#3376]
**Describe the bug**
If in the new UI, a selection session from Bb into openEQUELLA will work, but will be unable to return selections. When clicking return selections, the selection session will simply hang without committing the selection.

**To Reproduce**

1. Connect Blackboard to openEQUELLA via the REST integration.
2. Open a new UI selection session from Blackboard. 
3. Select some attachments and/or resource summary(ies). 
4. Click Return Selection
5. Note that nothing happens.
6. Repeat steps when the institution is in old UI mode.
7. Note that it works as intended.

**Expected behavior**
Selections should work in the new UI. 

**Platform:**

- OpenEquella Version: 2021.1+
- OS: Agnostic
- Browser: Agnostic

**Comment by snehanaik22** [comment]
Tested in new UI, able to make return selections using selection session from BB to OpenEQUELLA.
