### ISSUE TITLE
When moderating an item, attachment is editable when viewing the metadata.

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#3432]
**Describe the bug**
In the new UI (EBP), if the user moderates an item, a few controls, e,g. attachment control, will present the editing option even when viewing the metadata only.

**To Reproduce**
Select an item for moderation
Note that there is an Edit option for some controls even though Edit has not been selected for the item

**Expected behavior**
A view only display. Edit options only appear if Edit has been selected for the item

**Screenshots**

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**

Happening in new UI

**Comment by snehanaik22** [comment]
Tested.
