### ISSUE TITLE
eqos-5027: Sample reports header

### ISSUE THREAD

**Issue by emcgarrahan** [openequella/openEQUELLA#367]
Sample Reports images:

- Header image is cut off and the image is not the right size in HTML
- PDF download - EQUELLA image sized wrong
- Excel download - No EQUELLA image

**Comment by emcgarrahan** [comment]
<img width="863" alt="screen shot 2017-10-19 at 1 44 06 pm" src="https://user-images.githubusercontent.com/26549228/31793452-0ba2dd52-b4d4-11e7-85c8-48531f3e5677.png">

**Comment by emcgarrahan** [comment]
[reportFiles_hotitems.rptdesign5159.pdf](https://github.com/equella/Equella/files/1399985/reportFiles_hotitems.rptdesign5159.pdf)

**Comment by mrblippy** [comment]
Reports are institution specific. This would need to be fixed in the base institution that we distribute out (does anyone have a plan for that?)
