### ISSUE TITLE
Flickr images do not show in Full screen mode

### ISSUE THREAD

**Issue by emcgarrahan** [openequella/openEQUELLA#399]
Steps to Reproduce:

1. Contribute a Flickr image
2. Select Full screen from the Resource Summary page

Expected result: 
The image should show

Actual result:
Empty full screen mode

**Comment by mrblippy** [comment]
From the javascript console:Refused to display 'https://www.flickr.com/photos/58130019@N08/15131237412' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

Sounds like flickr stuff doesn't like allow being displayed in an iframe anymore
