### ISSUE TITLE
Create/fix a subset of Automated tests which we can use to verify the main functionality

### ISSUE THREAD

**Issue by doolse** [openequella/openEQUELLA#40]
It will be important to get a useful small subset of functionality tested with each build, particularly when we are about to make changes which will have a sweeping effect on the product, e.g. build tool and JPF runtime changes.

**Comment by emcgarrahan** [comment]
Benito and Chris to meet with the goal of closing this task by Wednesday the 9th:

- Fix scripts that can be fixed
- Comment out scripts that can't and make sure team is okay with why they can't be fixed

**Comment by edalex-ian** [comment]
With recent work with Travis builds and getting end-to-end tests plus unit tests going again this can well and truly be closed.
