### ISSUE TITLE
iTunesU attachments

### ISSUE THREAD

**Issue by emcgarrahan** [openequella/openEQUELLA#400]
Unable to successfully test the addition of iTunesU contributions.

If it is still supported, need to understand how to successfully configure an iTunesU institution ID for successful testing. This may have changed with the switch from iTunesU to Apple Podcasts.
If this feature is no longer supported/used, the following is suggested:

- Remove from UI
- Deprecate code
- Remove from Github pages documentation:
    - Contributions User Guide
    - Wizard Controls Reference Guide
    - Features Guide
    - Searching User Guide
    - etc

**Comment by doolse** [comment]
We have an autotest which is still passing, it uses: tamu.edu

**Comment by drewwills** [comment]
Out of curiosity -- does TAMU use Equella in some capacity?

**Comment by emcgarrahan** [comment]
@doolse 

I can get tamu.edu to come up, but since there are no valid tracks (the only file listed is no longer available), I can't actually play anything. So the concern is more that with the move from iTunesU to Apple Podcasts, the implementation is no longer a valid solution for folks who want to link to their content.. 

https://support.apple.com/en-us/HT208029
I can find all kinds of public content, however, I don't know how to get it to come up in Equella.

@drewwills - not to my knowledge. TAMU-C was but don't believe they use it any longer.
