### ISSUE TITLE
Custom link "Open in new window" option not functioning

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#4155]
**Describe the bug**
When setting up a custom link with Open in new window enabled, the link button in the left menu generated will always open the link in the same window.

![image](https://user-images.githubusercontent.com/32081370/169722545-d158ed8b-9bb9-4f91-b501-bb0ea37e584c.png)

**Comment by edalex-ian** [comment]
Was released as part of 2022.2.
