### ISSUE TITLE
missing language pack property security.privilege.ITEM_METADATA.VIEW_VIEWCOUNT

### ISSUE THREAD

**Issue by phette23** [openequella/openEQUELLA#4508]
**Describe the bug**

The `security.privilege.ITEM_METADATA.VIEW_VIEWCOUNT` property is absent from the language pack (checked most recent one available here, which is for 2022.1.0).

**To Reproduce**

1. Open the admin console
2. Open a collection definition
3. Go to Security > **Resource Metadata ACLs**
4. Add a new ACL
5. Under the "...then apply the following..." half of the condition, note that the first entry in the "who can" dropdown menu is "???security.privilege.ITEM_METADATA.VIEW_VIEWCOUNT???" because this property is missing.

**Expected behavior**

The text "view view counts for resources matching this rule" should be sorted into this menu at the appropriate spot. The line `security.privilege.ITEM_METADATA.VIEW_VIEWCOUNT=view view counts for resources matching this rule` needs to be added to admin-console.properties in the language pack around line no. 1717.

**Screenshots**

<img width="758" alt="Screen Shot 2022-11-29 at 8 32 38 AM" src="https://user-images.githubusercontent.com/1024833/204588998-43af1cb4-b07f-49fc-96fa-4bf969fd9dcb.png">

**Platform:**

- OpenEquella Version: we're still on 2019.2.6-Stable.OSE but I see no reason why this wouldn't affect 2022.1.0 too at least. You did not provide a reference language pack for 2022.2.0 so I can't say if the property is still missing.
- OS: MacOS 12.6.1
- Browser: n/a

**Comment by edalex-ian** [comment]
Thanks @phette23 , we'll look at including this in a future version.

(Edalex ref: OEQ-1421)

**Comment by edalex-ian** [comment]
This has been fixed for 2023.1.
