### ISSUE TITLE
Release 2022.2 package does not include a demo installer

### ISSUE THREAD

**Issue by nicholasdavidbrown** [openequella/openEQUELLA#4598]
The 2022.2 release of openEQUELLA package does not include a demo installer, which is inconsistent with previous releases. Following the https://openequella.github.io/guides/InstallationAdminGuide.html installation guide means the only option would be to build the installer via sbt.

I just want to flag this, as if it was intentional and you are no longer shipping demo releases, the documentation might need to be updated. Thanks.

**Comment by edalex-ian** [comment]
Hi @nicholasdavidbrown 

Thanks for raising the query. You are correct, we no longer publish builds for the open source version. To capture this, last year we added the 'Notice' section to the README.md.

So yes, if you want to use the open source one you do need to build yourself - however there are instructions in the CONTRIBUTING.md to help with this. Or, if you have a support contract then please contact your support provider and they'll easily provide you a pre-built version.

If you have any issues building, please don't hesitate to reach out.
