### ISSUE TITLE
Unable to load SCORM file located in OEQ Repository using the default Moodle Android app

### ISSUE THREAD

**Issue by ChandrashekarBemagoni** [openequella/openEQUELLA#4646]
**Environment:**
Moodle - 3.9.0
Moodle Android App - [Moodle App 4.1.0](https://moodledev.io/general/app_releases/v4/v4.1.0)
OpenEquella - https://github.com/openequella/openEQUELLA/releases/tag/2022.2.0

We have an openequella installation that we use as a content repository for our Moodle LMS. 
As part of this, we hosted some SCORM files in OEQ and access then from Moodle using the Repository approach. 

Settings on Moodle side:

![Screenshot from 2023-02-15 11-26-46](https://user-images.githubusercontent.com/7919831/218944866-1bc22eb3-f42d-48f0-851d-561addb9749c.png)

 
Settings on OEQ side:
 
![image](https://user-images.githubusercontent.com/7919831/218945180-c02c1eb8-93be-4b4c-9ae4-6a975133b997.png)

We mapped content to course in Moodle from Openequella and We are able view from Learner access in Web

![Screenshot from 2023-02-15 11-30-55](https://user-images.githubusercontent.com/7919831/218945533-a7a2a341-d26f-487d-a2db-f60a421040b2.png)

We are not able to view from Moodle App 
![image](https://user-images.githubusercontent.com/7919831/218945938-e23c1eac-66d7-44e3-a963-ca9c9666599f.png)

Please find the series of steps when we tried to download files

**Step1:**

Request:  Moodle API: https://cutsom-cr.com/webservice/pluginfile.php/835686/mod_scorm/package/0/Threads.zip?

```
Request Headers
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: 5edf1c7a-2192-4599-87d9-365ec256f3f3
Host: '*******'
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```
Response : In Response header, we are getting file location in OpenEquella with LTI token.

```
Date: Wed, 15 Feb 2023 06:43:36 GMT
Server: Apache/2.4.41 (Ubuntu)
Access-Control-Allow-Origin: *
Location: https://cutsom-cr.com/institute/integ/gen/f36d1968-97d7-4bfc-9527-9283411b3886/1/?attachment.uuid=3e7ce4b2-96cd-4042-8d04-6b623d1417e5&token=demouser1%3ALMS-LTI%3A1676443416000%3AQWIYRi5h0JcZZhtSbqG5dg%3D%3D
Content-Length: 0
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json; charset=utf-8
```

**Step2 :** 
 CR URL : 
Request https://cr-custom.com/institute/integ/gen/e2c36bee-9993-49d1-8cdd-973bd46021ab/1/?attachment.uuid=7732780b-2ff2-4fc0-9195-15d34a9fba83&token=demouser1%3ALTI%3A1676351914000%3A8FT6%2BahtEKnPdJK4M2ky2w%3D%3Dh

Request

```
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: 5edf1c7a-2192-4599-87d9-365ec256f3f3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://cr-custom.com/webservice/pluginfile.php/835720/mod_scorm/package/0/Embedded%20Systems%20-%20Automotive%20Electronics%20Overview.zip?token=0a620c52f0e9f65a26c645efb18c40c3
Host: **********************
Cookie: AWSALB=dDZp9XlYRIUaaGmyFKiHrvPV9YiRi5/R/tvpW93WhDjxRlxzWR3EKNNYve+YmsdKNJdeE5N0FWDNTbJvlXjx6ZGk+q4gssYhO9KCtGJkXO0zCG3qWgnTyxt6nI6o; AWSALBCORS=dDZp9XlYRIUaaGmyFKiHrvPV9YiRi5/R/tvpW93WhDjxRlxzWR3EKNNYve+YmsdKNJdeE5N0FWDNTbJvlXjx6ZGk+q4gssYhO9KCtGJkXO0zCG3qWgnTyxt6nI6o; JSESSIONID=B2A657CF4898B7A2DF509CACF5E6A89B; JSESSIONNODE=http://172.20.0.4:8080

```

Response : CR attachment Location

```
Date: Wed, 15 Feb 2023 06:43:36 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: AWSALB=FBdHBNMBb52cjGJml6BopNpdB95NHg2wCP82bmizDB4LOPfbULbRrOuSy/oUxa0PtQ8yRHhGEjei5/z44D2GhV3zGK0ht9JTtiflZgX4kSxQM4F0C0gRplckROeG; Expires=Wed, 22 Feb 2023 06:43:36 GMT; Path=/
Set-Cookie: AWSALBCORS=FBdHBNMBb52cjGJml6BopNpdB95NHg2wCP82bmizDB4LOPfbULbRrOuSy/oUxa0PtQ8yRHhGEjei5/z44D2GhV3zGK0ht9JTtiflZgX4kSxQM4F0C0gRplckROeG; Expires=Wed, 22 Feb 2023 06:43:36 GMT; Path=/; SameSite=None; Secure
Location: https://cr-custom.com/institute/file/f36d1968-97d7-4bfc-9527-9283411b3886/1/Embedded%20Systems%20-%20Automotive%20Electronics%20Overview.zip
P3p: CP="CAO PSA OUR"
Set-Cookie: JSESSIONID=47FFEA983CA5C6D77B87B55DFC476776; Path=/; Secure; SameSite=None
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
```

**Step3:**

Request : https://cr-custom.com/e2c36bee-9993-49d1-8cdd-973bd46021ab/1/Threads.zip

```
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: 5edf1c7a-2192-4599-87d9-365ec256f3f3
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://cr-custom.com/institute/integ/gen/f36d1968-97d7-4bfc-9527-9283411b3886/1/?attachment.uuid=3e7ce4b2-96cd-4042-8d04-6b623d1417e5&token=demouser1%3ALMS-LTI%3A1676443416000%3AQWIYRi5h0JcZZhtSbqG5dg%3D%3D
Cookie: AWSALB=FBdHBNMBb52cjGJml6BopNpdB95NHg2wCP82bmizDB4LOPfbULbRrOuSy/oUxa0PtQ8yRHhGEjei5/z44D2GhV3zGK0ht9JTtiflZgX4kSxQM4F0C0gRplckROeG; AWSALBCORS=FBdHBNMBb52cjGJml6BopNpdB95NHg2wCP82bmizDB4LOPfbULbRrOuSy/oUxa0PtQ8yRHhGEjei5/z44D2GhV3zGK0ht9JTtiflZgX4kSxQM4F0C0gRplckROeG; JSESSIONID=47FFEA983CA5C6D77B87B55DFC476776; JSESSIONNODE=http://172.20.0.4:8080
Host: *************
```

Response : SCORM file

We also developed custom android , from there also we are not able to download.

Any suggestion to get download the file into android app?

**Comment by edalex-ian** [comment]
Did you get this resolved in the end @ChandrashekarBemagoni ?
