### ISSUE TITLE
SUMMARY_VIEWED and CONTENT_VIEWED events are not getting stored in database

### ISSUE THREAD

**Issue by kapil-bunni** [openequella/openEQUELLA#4683]
**Describe the bug**
- Openequella have the default reports and these default reports can be downloaded from admin console launcher, these reports are also present in the sample institute "Vanilla".
- Some reports are giving the empty result for example : "hotfiles.rpt", "hot items.rpt".
- When I'm trying to solve the issue I checked the report in "BIRT Report Designr" under the datasets the query is written as :

```sql
 select ls.text as "collectionName", ls2.text as "itemName", sq."count", 
       i.item_definition_id as "collection_id", i.uuid as "uuid", i.version as "version"
from item i
inner join base_entity be on i.item_definition_id = be.id 
inner join
(
select a.data1 as uuid, cast(a.data2 as int) as version, count(a.data1) as "count" from audit_log_entry a
 where a."timestamp" >= ? and a."timestamp" < ? and 
 a.event_type = 'SUMMARY_VIEWED' and a.institution_id = CURRENT_INSTITUTION
 group by a.data1, a.data2
) sq
on sq.uuid = i.uuid and sq.version = i.version and i.institution_id = CURRENT_INSTITUTION
inner join language_string ls on be.name_id = ls.bundle_id
inner join language_string ls2 on i.name_id = ls2.bundle_id
order by "count" desc
```

- Where the event_type in table audit_log_entry dont have the event_type like "SUMMARY_VIEWED" and "CONTENT_VIEWED" etc.
- Only the event_types "LOGIN", "LOGOUT", "HIERARCHY", "STANDARD" are recorded in database.
- And the reports like "hotfiles.rpt", "hot_items.rpt", "top_viewed.rpt" are based on the event_type in audit_log_entry table.
- Need a way to store "SUMMARY_VIEWED" and "CONTENT_VIEWED" enums in database on the appropriate action performed by user.

**To Reproduce**
generate the report hotfiles.rpt, you will see empty report, try opening the report in BIRT report Designer to see the query.  

**Expected behavior**
Report should be generated with the appropriate data.

**Stacktrace**
No stacktrace simply gives an empty report

- Ubuntu 22.04
- Browser [e.g. Chrome, Firefox]

-Please try to explain on what actions triggered the enums "SUMMARY_VIEWED" and "CONTENT_VIEWED" are stored in DB in audit_log_entry.

**Comment by PenghaiZhang** [comment]
HI @kapil-bunni ], when you installed OEQ , did you choose the option which will allow the view of content to be stored in table `audit_log_entry`

![image](https://user-images.githubusercontent.com/47203811/230236060-f149009a-70d6-4c83-b940-618e06cb3429.png)
