### ISSUE TITLE
Does OpenEquella support the feature of a Content Authoring Tool?

### ISSUE THREAD

**Issue by ChandrashekarBemagoni** [openequella/openEQUELLA#4698]
Dear Team,

We are interested in knowing if OpenEquella supports the Content Authoring Tool feature. If it does, we would like to understand how to configure it. Additionally, we would like to know if there is a possibility of integrating any Content Authoring tools such as iSpring.

**Comment by edalex-ian** [comment]
Hello,

The typical use case is to store the course content - including packages - within oEQ and then publish them to an LMS or the like from oEQ. So for example publish a standard package from iSpring, and then create an item in oEQ with the package as an attachment. Then in your LMS embed that content via a selection session.

Hope that clarifies.

Out of interest, do you plan on submitting any of your work for 'Hyphen' back to the core repository? We are open to contributions.
