### ISSUE TITLE
Does OpenEquella support Single Sign-On (SSO) integration with Keycloak?

### ISSUE THREAD

**Issue by ChandrashekarBemagoni** [openequella/openEQUELLA#4699]
I have a question regarding OpenEquella's capabilities and integration options. Specifically, I would like to inquire whether OpenEquella supports Single Sign-On (SSO) integration with Keycloak.

Could you kindly provide information on whether such integration is possible and, if so, any relevant documentation or resources that could assist with the configuration process?

Thank you very much for your time and assistance.

**Comment by edalex-ian** [comment]
Hello,

Please see the CAS and External Authentication user management modules in the admin console.

![2023-05-24-105245_466x588_scrot](https://github.com/openequella/openEQUELLA/assets/43919233/242830ed-ace4-43e3-81b7-c24253252378)

It is with the use of these people typically enable SSO solutions. I'm not specifically across an instance where someone has integrated with Keycloak though. But maybe something could be achieved. If you would like a more detailed discussion around SSO the Edalex Support team or Consulting team may be a better option - they often directly assist adopters with this.

Documentation is also available at https://openequella.github.io/ but unfortunately this can only be searched via the source files available from the repo at https://github.com/openequella/openequella.github.io . Again, Edalex does have a more comprehensive documentation offering - with search. If you get in contact someone should be able to help you out with that.

Sorry I can't offer anything more specific, but hopefully the above gives you some starting points.
