### ISSUE TITLE
CORB on accessing CR Video files from LMS 

### ISSUE THREAD

**Issue by ChandrashekarBemagoni** [openequella/openEQUELLA#4736]
We have uploaded several video content files in the Content Repository (CR) and attached them to the LMS course using the Repository pattern.

However, when users attempt to access these videos from the LMS, they encounter an issue. The error message states that there is a problem related to Cross-Origin Read Blocking (CORB).

Upon investigation, we discovered that the default Content Type for the CR is set to text/html. However, for video files, the client expects video headers. This mismatch between the expected and received headers is causing the browser to throw the CORB error.

Has anyone else encountered a similar issue before? We would appreciate any insights or suggestions on how to resolve this problem.

**Comment by edalex-ian** [comment]
Hi @ChandrashekarBemagoni 

For general discussion queries like this, it'd be best to post to the equella-users mailing list: https://groups.google.com/a/apereo.org/g/equella-users
