### ISSUE TITLE
Installation error yarn apt repo not found on debian

### ISSUE THREAD

**Issue by ChristianMurphy** [openequella/openEQUELLA#512]
running the example instructions as the super user:

```sh
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
apt-get update
```

results in

```
E: The method driver /usr/lib/apt/methods/https could not be found.
```

**Comment by ChristianMurphy** [comment]
https://askubuntu.com/questions/165676/how-do-i-fix-a-e-the-method-driver-usr-lib-apt-methods-http-could-not-be-foun

**Comment by doolse** [comment]
Those install commands where specifically for ubuntu 17.10, are you using that or debian? I honestly don't think we should bother putting our own instructions for installing the dev tools and instead rely on the instructions on the given tools homepage instead.

**Comment by ChristianMurphy** [comment]
> Those install commands where specifically for ubuntu 17.10, are you using that or debian?

Debian

> don't think we should bother putting our own instructions for installing the dev tools and instead rely on the instructions on the given tools homepage instead.

For basic installation, that could be a good idea.
It may still be valuable to capture details around last tested versions and any installation quirks.
