### ISSUE TITLE
Expose the User Profile as a REST endpoint - GET

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#544]
Enable a REST endpoint to GET the logged-in user profile.  Part of the wider effort to handle the CRUD operations of the logged-in user profile via the REST API.

`/api/usermanagement/local/user/profile`

Should return:
```
{
      "id": "user-uuid...",
      "username": "...",
      "firstName": "...",
      "lastName": "...",
      "emailAddress": "..."
}
```

**Comment by doolse** [comment]
Issue #532 probably already covers this specific case with it's new `/api/content/currentuser` endpoint
