### ISSUE TITLE
REST entity endpoints: Available count is wrong when results filtered by lack of privileges

### ISSUE THREAD

**Issue by abidingotter** [openequella/openEQUELLA#547]
E,g., 
http://insturl/api/course?q=&length=30 will fall back to LIST_(ENTITY) privilege.  If user does not have this privilege then no results are returned, but the available count will be the total number of entities in the database.

**Comment by doolse** [comment]
I was aware of this and was tempted to change it from 'available' to something else as there's nothing we can really do to get an accurate count without storing it in lucene or something. I propose we simply advise in the documentation that the available is just a guess.
