### ISSUE TITLE
Move security manager from admin console into the web

### ISSUE THREAD

**Issue by abidingotter** [openequella/openEQUELLA#548]

**Comment by abidingotter** [comment]
Current state of this issue:
A minimum (very minimum) viable product is committed.  It only shows the top level Institution priviliges, plus entities that have current REST endpoints.
Jolse suggests that we create a new REST endpoint to the return the entire tree structure seen in the admin console, and another endpoint that would give the privileges for any level in the tree.

**Comment by cbeach47** [comment]
:+1: 

Exciting to see this chunk of the admin console migration taking shape.
