### ISSUE TITLE
"More" hierarchy topic doesn't return you to the full list of hierarchies if you've already browsed a different one.

### ISSUE THREAD

**Issue by carl-edalex** [openequella/openEQUELLA#556]
If you have more than 5 (I think) hierarchy topics, EQUELLA will automatically create a "More" topic link in the left-hand navigation.  That takes you to the <EQUELLA>/hierarchy.do?hier.topic=ALL page where it lists all of the hierarchy topics.

If you descend into a hierarchy topic (that has more than 1 level) but then click on the "More" topic, your view doesn't change.

If you then go to a different topic and only view the top level but don't descend into any subtopics, and then click the "More" button, it takes you back to the previous topic ... it seems to remember the last hierarchy topic that you went into (that was deeper than 1 level).

This "memory" seems to last for your logged in session.  You could go to the Home, or perform a search or do something else, but when you click on the "More" button, it pulls up the last hierarchy topic that you went past the first level.

Reported in 6.4, tested in 6.5, 6.6 and it is broken there as well.

**Comment by cathfitz** [comment]
Still an issue

**Comment by carl-edalex** [comment]
Still an issue.

**Comment by snehanaik22** [comment]
Tested.
