### ISSUE TITLE
New course selector now requires LIST_COURSE_INFO privilege

### ISSUE THREAD

**Issue by doolse** [openequella/openEQUELLA#603]
Because the course selector uses the course search API it now requires LIST_COURSE_INFO, whre as it used to just show you any courses. Either we need 
 - a migration (sigh.)
 - or make it not need a permission again (sigh)
 - just make sure everyone knows about this

**Comment by cbeach47** [comment]
I don't have a strong opinion either way, but it seems sufficient to leave as-is, and note that when upgrading, you'll need to apply this permission - similar to when `PURGE_ITEM` was introduced.
