### ISSUE TITLE
Activate attachments screen: mismatched dropdown widths

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#650]
**Describe the bug**
The new course search drop down is a different width to the citation dropdown in the form which makes it look inconsistent.

**To Reproduce**
1. Go to 'Manage Activations'.
2. Click on an item's 'Activate' button.
3. Observe that each drop down is of an inconsistent length.

**Expected behavior**
The two dropdowns should line up.

**Screenshots**
![image](https://user-images.githubusercontent.com/24543345/49845191-d2daeb00-fe19-11e8-9209-91ef33e69254.png)

**Platform:**
 - OpenEquella Version: 2018.2
 - OS: Ubuntu 18.04.1
 - Browser: Firefox

**Comment by abidingotter** [comment]
The proper fix would be to bring back the same dropdowns that the course selector is using, and then fix the widths of the dropdowns around the app that don't look good.

**Comment by edalex-ian** [comment]
This might have been fixed. @SammyIsConfused could you please have a look?

**Comment by SammyIsConfused** [comment]
> This might have been fixed. @SammyIsConfused could you please have a look?

@edalex-ian Unfortunately this one is still open. Current develop has mismatched dropdown widths.
