### ISSUE TITLE
Protect admin URL from being masked by Institutions

### ISSUE THREAD

**Issue by goetzk** [openequella/openEQUELLA#675]
**Is your feature request related to a problem? Please describe.**

If an institution is imported using the same top level url as admin.url (nothing warns this is happening) visits to "/institutions.do?method=admin" result in errors similar to the below.

```
Access denied
Sorry you do not have access to view the page you requested.
Only admin site access

The URL you requested was:
http://192.168.56.101/institutions.do?method=admin

Authentication:
You are not logged into the system

Action:
Go back
```

**Describe the solution you'd like**
oE's admin area should be protected from institutions masking it just as other institutions are protected.

**Comment by edalex-ian** [comment]
Ideally some simple validation would be useful. Have labelled as 'help wanted' in case anyone in the community would like to contribute.

**Comment by goetzk** [comment]
afaik this problem hasn't been solved yet so here is your ping.

**Comment by goetzk** [comment]
I will not be playing ticket pong with bots, after this I will simply allow the issue to bee expired.

**Comment by abidingotter** [comment]
I think this stale bot is far too aggressive. I will tag the issue to make sure it doesn't go stale

**Comment by goetzk** [comment]
Thanks @abidingotter (I'm certainly unimpressed by the bot)
