### ISSUE TITLE
Changing "Number of results per page" under "Manage Resources" in new UI does not work

### ISSUE THREAD

**Issue by nelson-edalex** [openequella/openEQUELLA#739]
**Describe the bug**
Changing "Number of results per page" under "Manage Resources" in new UI does not work.
It will always display only 10 search results.

**To Reproduce**
1. Enable new UI.
2. Go to 'Manage resources'
3. Click 'Preference' dropdown and select 'Maximum'
4. Scroll down to see the search result page size

**Expected behavior**
The number of results in the page should be 100.

**Platform:**
 - OpenEquella Version: 6.6.r17

**Comment by edalex-ian** [comment]
Hi @nelson-edalex 

We've been looking at the way the 'screen options' are done in the New UI and are planning a rethink. Once implemented this will also solve your current issue, but hopefully also improve UX.

Do you need it back ported to 6.6, or will it be sufficient if we just back port to 2018.2?

IS.
