### ISSUE TITLE
New UI: User should be able to easily tell who they are logged in as

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#796]
**Is your feature request related to a problem? Please describe.**
Currently the only way to tell who is logged into openEquella in the new ui is to click on the user icon, and going to the My Preferences page
![dashboard page](https://user-images.githubusercontent.com/4625498/55045020-8944a200-5090-11e9-9b07-8faff9b75be6.jpg)

 
**Describe the solution you'd like**
Since we are using material ui it makes sense to do something similar to what is done in the google apps. Where the name appears as a tooltip when you hover over the icon
![google tooltip](https://user-images.githubusercontent.com/4625498/55045354-9e6e0080-5091-11e9-8acb-a2549feec1ad.png)

**Comment by edalex-ian** [comment]
Definitely in and lookin' good. :+1:
