### ISSUE TITLE
Date fields in new Course Editor do not display year

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#802]
When adding a Start Date and End Date for a course in the new course editor accessed from Settings, Integrations, the year doesn't display. It is possible that courses are valid across years, so the year should be displayed.

**To Reproduce**

1. Go to Courses from Settings, Integrations
2. Edit an existing course or add a new one
3. Select Start Date and End Date
4. Note that no year displays

**Expected behavior**
The year should display as part of the date. Note that in the new Login Notice Editor, the schedule date displays as dd/mm/yyyy - perhaps these dates could match this format

**Screenshots**
![image](https://user-images.githubusercontent.com/32081370/55296969-7ead5280-546c-11e9-9fea-a66bd9d77fd0.png)

**Platform:**

- OpenEquella Version: [e.g. 6.6, 2018.2]

- Browser [e.g. Chrome, Firefox]

**Comment by abidingotter** [comment]
Hmm, had Edalex label yet was still closed by stale bot?

**Comment by edalex-ian** [comment]
> had Edalex label yet was still closed by stale bot?

Initially there was a typo so the Edalex ones were missed. :(

**Comment by cathfitz** [comment]
Closing as this course editor was removed
