### ISSUE TITLE
Course editor - when editing any course field, the Unique Individuals field becomes mandatory

### ISSUE THREAD

**Issue by cathfitz** [openequella/openEQUELLA#803]
**Describe the bug**
When editing an existing course in the Course Selector accessed from Settings, Integrations, the Unique Individuals field is being set to mandatory and won't allow the changes to be saved until a value has been added to that field. Editing any field for the course seems to trigger this. The Unique Individuals field does not appear as mandatory (red) until the user tries save the changes they've made.

**To Reproduce**

1. Go to Courses from Settings, Integrations
2. Open an existing course
3. Change any field (select a value, change a text name etc.)
4. Click Save
5. The Unique Individuals field is highlighted in red, and the changed can't be saved until a value is selected in the this field.

**Expected behavior**
The Unique Individuals field should never be a mandatory field

**Screenshots**

![image](https://user-images.githubusercontent.com/32081370/55297977-af928500-5476-11e9-9674-f1e06a01ce12.png)

**Platform:**

- OpenEquella Version: [e.g. 6.6, 2018.2, 2019.1 unstable]
- OS: [e.g. Windows 10]
- Browser [e.g. Chrome, Firefox]

**Additional context**

**Comment by edalex-ian** [comment]
Heya @mrblippy 

So has this been tested in 2019.2 and thereby ready to close?
