### ISSUE TITLE
OAuth token servlet requires redirect_uri even when using client_credentials grant

### ISSUE THREAD

**Issue by doolse** [openequella/openEQUELLA#810]
**Describe the bug**
The oEQ OAuth token servlet (`oauth/access_token`) makes the `redirect_uri` parameter mandatory even when being used with `client_credentials` grant. Also the error messages are broken language strings.

**To Reproduce**
An OAuth client using `client_credentials` grant doesn't supply the `redirect_uri`.

**Expected behavior**
Using the `client_credentials` grant should work without the `redirect_uri` parameter being specified. The error messages should work properly.

**Platform:**
- OpenEquella Version: [6.5 - 2019.1]

**Comment by edalex-ian** [comment]
@doolse could you please advise where this issue's at?

Thanks.

**Comment by doolse** [comment]
This is ready to test in 2018.2  and 2019.1. It probably not worth backporting as it was only an issue because of the Cloud provider work

**Comment by edalex-ian** [comment]
For some reason I can't assign this to @mrblippy , but could you please test it? (Maybe self assign.)

**Comment by mrblippy** [comment]
This is working in 2019.1, but not in 2018.2

**Comment by SammyIsConfused** [comment]
Modified milestone to 2019.2, since it's working in 2019.1.
