### ISSUE TITLE
Blackboard LTI/REST course list population is slow

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#818]
**Describe the bug**
Add to External System > Blackboard LTI/REST config > course list is populated on-server and pushed to the client.  When there are hundreds of courses, this results in multiple Bb requests from the oE server and creates a sizeable delay for the client.

**To Reproduce**

1. Configure a oE/Bb LTI/REST integration
2. Navigate to an item
3. Click on 'Add to external system'
4. Select the oE/Bb LTI/REST configuration
5. If there are several hundred courses available to your user in Bb, you notice the delay in the course list being built out.

**Expected behavior**
The user should not experience the delay, however, when this gets ported to the 'new UI', it'd be feasible expose the pagination of courses to the user.

**Platform:**
- OpenEquella Version: [e.g. 2019.1 Alpha]

**Additional context**
This occurs in the other external system configuration types (Brightspace, Canvas, etc) as well.

**Comment by cbeach47** [comment]
Moving this to 2020.3

**Comment by cathfitz** [comment]
@cbeach47 is this still earmarked for 2021.1?

**Comment by cathfitz** [comment]
@cbeach47 is this still being looked at?
