### ISSUE TITLE
Various non-primary openEQUELLA LTI Tool Placements in Blackbboard result in a 404

### ISSUE THREAD

**Issue by cbeach47** [openequella/openEQUELLA#847]
openEQUELLA's LTI Tool Placements in Blackboard of Course Content Tool (no deep linking), System Tool,  and Administrator Tool result in a 404 error from oE:  not found - /dev/electOrAdd

**Comment by cbeach47** [comment]
Putting this on the Backlog.  If adopters want these features, please make some noise.  :)

**Comment by edalex-ian** [comment]
Heya @cbeach47 , could you expand out the acronyms CCT, CT and AT please?

**Comment by cbeach47** [comment]
Ah yes -
CCT = Course Content Tool
AT= Administrator Tool
ST = System Tool

From Blackboard's LTI Tool Provider > LTI Placement configuration:

![image](https://user-images.githubusercontent.com/28629296/82615478-1c437400-9b90-11ea-8415-ef288dd104a2.png)
