### ISSUE TITLE
EQUELLA logs HTTP referrer incorrectly if HEAD method is issued in MS Edge

### ISSUE THREAD

**Issue by nelson-edalex** [openequella/openEQUELLA#861]
**Describe the bug**
When using Microsoft Edge to access EQUELLA attachments, sometimes a HEAD method request is issued by Edge before making a GET request to the file.

In this case, since the HEAD request is initiated by Edge itself, there is no HTTP referrer.  The HTTP referrer only presents during the GET request.

While EQUELLA is in SMART logging mode, it logs the HEAD requests with null HTTP referrer.  As this creates a valid session, it does not log the GET request with HTTP referrer again.

**To Reproduce**

1. Open an EQUELLA file attachment in Moodle with MS Edge
2. Verify the HEAD request presents in the web server log
3. Check audit_log_entry table

**Expected behavior**
HTTP referrer should be logged as the Moodle URL.

**Screenshots**

**Stacktrace**
If applicable, a stacktrace to help explain your problem.

**Platform:**

- OpenEquella Version: 6.6
- Browser: Microsoft Edge

**Additional context**
Chrome and Firefox did not send HEAD method request and do not have this issue.
It would be good to ignore HEAD and OPTION method in audit logging.

**Comment by cathfitz** [comment]
@nelson-edalex Is this still required?

**Comment by nelson-edalex** [comment]
Yes, this error happens on Microsoft Edge and some clients are using it as default browsers.

**Comment by abidingotter** [comment]
I’m not sure if we would want to stop logging a HEAD request.  A HEAD may not be followed up by a GET, in which case we missed the fact the user is viewing the content. (would only apply if user has already viewed it recently and it’s in their cache, and so also only affects NORMAL logging)

**Comment by abidingotter** [comment]
Proposed fix is that we still audit HEAD and OPTIONS requests, but for the purposes of “smart” logging we don’t register it as a viewing.  Therefore any follow-up GET request will also be logged, along with the referrer header.
