### ISSUE TITLE
Provide support for Docker container-based deployment

### ISSUE THREAD

**Issue by viztastic** [openequella/openEQUELLA#94]
Is it possible to simplify the dev/prod setup by getting the setup into a Docker-compose file so that the developer/deployer simply needs to run `docker-compose up` command?

**Comment by drewwills** [comment]
@viztastic -- I believe that this is an idea that belongs on our road map.  I'm not sure how quickly we could possibly handle it, but perhaps it isn't too far off.  We have our hands full getting the application launched on GitHub (but we've come a long way).

**Comment by xicubed** [comment]
@drewwills  @viztastic I'm trying to make one myself to evaluate Equella... Can you add me to Slack or something where we can share our findings? I have a boisestate.edu email address if you can "whitelist" it or something. Or we could use this "thread".

**Comment by drewwills** [comment]
@xicubed -- please send an email to neal dot caidin at apereo dot org.  I believe he can add your institution.

**Comment by cbeach47** [comment]
Note - It would still be useful to have a docker-compose version of oEQ.  Enhancements are welcome!  :)
