### ISSUE TITLE
sbt clean should also clean JS folders

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA#943]
**Describe the bug**

A number of people have experienced issues when coming back to build oEQ after a break. This has typically come down to out of date files in the core `js` folder (`Source/Plugins/Core/com.equella.core/js/`). The solution is to go into that folder and do a `npm run clean`, but this should be part of the root `sbt clean` seeing it is also the one triggering the creation of this intermediate folder.

**Comment by ChristianMurphy** [comment]
resolved in #955

**Comment by abidingotter** [comment]
Doesn't work on Windows, and so you can't even do `sbt clean`, but will open up another issue.
