### ISSUE TITLE
Can upload multiple attachments to attachment controls that don't allow multiple attachments

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA#985]
**Describe the bug**
The only way you seem to be able to do it is by clicking 'Add a resource', drag and drop is not affected.

**To Reproduce**

1. Import the attached collection definition[One attachment allowed.zip](https://github.com/apereo/openEQUELLA/files/3279202/One.attachment.allowed.zip)
2. Start a contribution wizard
3. Click the 'Add a resource button'
4. Click Browse, and add multiple files
5. Click the green add button
6. Click save, notice that you have been able to save the item, even though the attachment control was not set to allow multiple attachments

**Expected behavior**
When you drag and drop multiple files using drag and drop, the following message displays, and wont let you save until that attachment control only has one attachment
![drag and drop](https://user-images.githubusercontent.com/4625498/59317794-d3403a00-8d07-11e9-842f-dae113234f23.PNG). 
The same thing should happen for non drag and dropped files

**Platform:**

- OpenEquella Version: 2018.2 2019.1
- OS: Windows 10
- Browser Chrome

**Comment by abidingotter** [comment]
A related/unrelated issues is: if you use drag and drop, and move to another page in your wizard and ignore the validation error, it then allows you to publish the item.  If you go back to the page with your attachment control on it, you will see the validation message has gone.

**Comment by abidingotter** [comment]
The server side was treating an attachment control with no max limit selected as an unlimited attachment control, however the default is to only allow 1 attachment.
Thankfully the server-side fix has negated the need to delve into Purescript land :)  
The related/unrelated issue is also fixed as a result.
